### ISSUE TITLE
Password Requirements 

### ISSUE THREAD

**Issue by TanmayKalra09** [AlfiyaSiddique/TastyTrails#1]
We can show these password requirements in bullets points for better understanding of user

Please assign me this issue under GSSOC Extended 2024 :)

![Screenshot 2024-10-01 182707](https://github.com/user-attachments/assets/74293e20-fc10-4cab-96cd-7de59131c181)

**Comment by TanmayKalra09** [comment]
yes i have set up project locally

**Comment by AlfiyaSiddique** [comment]
Okay great!
Assigning it to you.
