### ISSUE TITLE
BUG: Recipe data is not Populated (Imp) 

### ISSUE THREAD

**Issue by AlfiyaSiddique** [AlfiyaSiddique/TastyTrails#102]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe your issue

Due to some bug the recipe data is not populating please check this is asap and provide a solution

### Steps to reproduce

Check Receipe page 
Chec main meals page

### What was the expected result?

The recipe card data should populate

### Proposed solution

Please add your solution in the comment

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
If anyone is interested in fixing this issue please comment

**Comment by AlfiyaSiddique** [comment]
This is an important bug need to be fixed asap

**Comment by AlfiyaSiddique** [comment]
![image](https://github.com/user-attachments/assets/b6c80c59-bb4e-4700-a38b-e5881c9da42f)

**Comment by yours7himanshu** [comment]
@AlfiyaSiddique I can fix this too

**Comment by AlfiyaSiddique** [comment]
@yours7himanshu  assiging to you

**Comment by AlfiyaSiddique** [comment]
Fix this on priority

**Comment by yours7himanshu** [comment]
> Fix this on priority

Okay I wanna ask one thing..like previously I had worked repo and my PR has now merged...So I wanted to delete that forked repo and then fork it again for solving the new issue.It would be fine or it's a bad practice?

**Comment by yours7himanshu** [comment]
> Fix this on priority

didi jo apne backend server jo appne deploy kiya tha uska url dena pls asap

**Comment by yours7himanshu** [comment]
> Fix this on priority
@AlfiyaSiddique 
I fixed it..The two problems i got and i changed that first---> In the backend section when u are using cors and on the allowedOrigin function u did'nt mention the frontend localhost url so anyone who is solving the issue using localhost will face a cors  issue..

2nd one which was the main cause of the recipe.jsx and not causing the recipe to be populated is this - In your original code, you destructured the response data like this:

javascript

const { recipes, pagination } = response.data;

However, pagination is already a state variable in your component. By naming the destructured value from response.data as pagination, you were unintentionally creating a conflict between the local variable pagination (from the API response) and the state variable pagination.
![Screenshot from 2024-10-07 12-46-59](https://github.com/user-attachments/assets/83f1090b-005f-4570-bb27-d67765da9dc0)

**Comment by sadath2001** [comment]
i think this is related to pagination.

**Comment by sadath2001** [comment]
i can fix this

**Comment by sadath2001** [comment]
Raised a PR #129
