### ISSUE TITLE
BUG: Remove checking I'm a GSSOC'24 Ext contributor * as mandatory files to check from all issue templates

### ISSUE THREAD

**Issue by AlfiyaSiddique** [AlfiyaSiddique/TastyTrails#103]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe your issue

 Remove checking I'm a GSSOC'24 Ext contributor * as mandatory from all issue templates
Not all contributors may be gssoc contributors

### Steps to reproduce

Present in Issue template when opening a issue

### What was the expected result?

 I'm a GSSOC'24 Ext contributor * This box can left unchecked and still the issue can be submitted

### Proposed solution

Please add your solution in the below comment

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by yours7himanshu** [comment]
@AlfiyaSiddique I will do that assign to me😊

**Comment by AlfiyaSiddique** [comment]
@yours7himanshu assigned

**Comment by yours7himanshu** [comment]
> @yours7himanshu assigned

raised a PR please review it

**Comment by sadath2001** [comment]
i can work on this

**Comment by AlfiyaSiddique** [comment]
@sadath2001 go ahead

**Comment by AlfiyaSiddique** [comment]
But please do get assigned before start working from next time

**Comment by sadath2001** [comment]
HI @AlfiyaSiddique , sure. thank you for the feedback.
