### ISSUE TITLE
ENHANCEMENT: Improvement in Sign Up page

### ISSUE THREAD

**Issue by MrunalKashid02** [AlfiyaSiddique/TastyTrails#104]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

![Screenshot 2024-10-06 165325](https://github.com/user-attachments/assets/5d2143a1-3fd1-4b4d-9f17-44f0bffd7fc6)
Existing Issue- For Sign Up page FirstName LastName Username And Email Display Black color font which not user friendly

### Component

https://delightful-daifuku-a9f6ea.netlify.app/signup

### It should be implemented because

This issue must resolve user may not able to see fieldname

### Would you like to work on this issue?
I want work on this issue

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by MrunalKashid02** [comment]
Please Assign this issue to me

**Comment by AlfiyaSiddique** [comment]
@MrunalKashid02 this issue is already in development.
Closing this issue.
Thanks for showing interets.
