### ISSUE TITLE
ENHANCEMENT: Add Favicon & Improve Title.

### ISSUE THREAD

**Issue by ShivamTiwari0214** [AlfiyaSiddique/TastyTrails#106]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

![image](https://github.com/user-attachments/assets/0abbcf14-6b02-4cb0-914b-a03f51c93b77)

**Improving Title:** I propose enhancing the page title to be more descriptive and SEO-friendly. Instead of a generic title, we can use something like **"_TastyTrails - Explore Delicious Recipes Around the World_"** to improve visibility and user engagement.

**Adding Favicon:** I plan to add a favicon to improve the site's branding and visual appeal. The favicon could feature a simple logo or icon representing food or trails, which users can easily associate with the TastyTrails brand.

### Component

**Title**: I will update the static title across all pages of the application by modifying the public/index.html file in the React frontend. This ensures that the title is meaningful and consistent throughout.

**Favicon**: A favicon will be added to the same public/index.html file, so it is displayed consistently across all routes and screens in the application.

### It should be implemented because

**Improving the Title:** A more descriptive, static title improves user engagement and makes the website more discoverable through search engines. A well-crafted title helps convey the purpose of the application at a glance, improving user experience.

**Adding a Favicon:** A favicon strengthens brand recognition, making the website easily identifiable in browser tabs and bookmarks. It also adds a professional touch, contributing to the overall visual appeal and usability.

Please assign this issue to me @AlfiyaSiddique .

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@ShivamTiwari0214 Adding favicon is already under development

**Comment by ShivamTiwari0214** [comment]
Title should also be changed. I propose "TastyTrails - Explore Delicious Recipes Around the World"

> @ShivamTiwari0214 Adding favicon is already under development

**Comment by AlfiyaSiddique** [comment]
@ShivamTiwari0214 too small issue to be assigned
