### ISSUE TITLE
Adding rate us Frontend

### ISSUE THREAD

**Issue by Aditijainnn** [AlfiyaSiddique/TastyTrails#11]
adding rate us option in the bottom please assign this to me under hacktober fest and gssoc ext 24

**Comment by AlfiyaSiddique** [comment]
Hi @Aditijainnn 
Welcome to TastyTrails. 🎉

Can you please describe where exactly you will add this rate us feature?
and how it will improve the web app and be useful to users.

**Comment by Aditijainnn** [comment]
> Hi @Aditijainnn Welcome to TastyTrails. 🎉
> 
> Can you please describe where exactly you will add this rate us feature? and how it will improve the web app and be useful to users.
The Rate Us feature at the bottom will allow users to provide quick feedback, improving the app based on user experience. It also enhances user engagement

**Comment by AlfiyaSiddique** [comment]
Okay, Understood!
Are you going to do it with the backend like storing the feedback data or message in the database so that it can be analyzed?

**Comment by Aditijainnn** [comment]
> Okay, Understood! Are you going to do it with the backend like storing the feedback data or message in the database so that it can be analyzed?

i can try linking it with backend but i am not that efficient dealing with backend so will you able to guide

**Comment by AlfiyaSiddique** [comment]
Okay no worries, you can Implement the rate us feed back form frontend, Assigning this issue to you.
Implement the feedback frontend only. Make it in star format with a optional message box.
You can also share the designs for approval before implementing.

**Comment by Aditijainnn** [comment]
> @Aditijainnn Okay no worries, you can Implement the rate us feed back form frontend, Assigning this issue to you. Implement the feedback frontend only. Make it in star format with a optional message box. You can also share the designs for approval before implementing.

ok sure
