### ISSUE TITLE
FEATURE: Making the site a Progressive Web App

### ISSUE THREAD

**Issue by sadath2001** [AlfiyaSiddique/TastyTrails#110]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Hi,
I would like to implement the PWA feature here that would enable offline caching in case of connectivity loss.

ETA: 2-3 days

### Component

Basically the whole website

### It should be implemented because

Ease of access to application even in case of network disconnection

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@sadath2001 go ahead

**Comment by sadath2001** [comment]
hi @AlfiyaSiddique , i have made the change, here is thevideo:
https://drive.google.com/file/d/19BwXc1UG2tJL03UmEfbhvew4W9uEZfr_/view?usp=sharing

kindyl check and let me know so that i can raise a PR

**Comment by AlfiyaSiddique** [comment]
@sadath2001 looks good, please raise the PR
