### ISSUE TITLE
BUG: Recipies dont get populated when starting fresh

### ISSUE THREAD

**Issue by sadath2001** [AlfiyaSiddique/TastyTrails#111]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe your issue

Hi,
I found a bug recently.
When i create a new account, and then i login, initially there would be no recipies.
When i try adding the recipie, it shows internal error.

### Steps to reproduce

1. Create a new account
2. Add a new recipie
3. You could see an error

### What was the expected result?

The recipie shouldve been added succesfully

### Proposed solution

i could see that there is a slight issue in the code:
 const lastDocument = await Recipe.findOne().sort({ _id: -1 }); 
        const unique = lastDocument._id.toString()
      
     the above code would fetch the last documentid to generate a unique id.
Since there is no last document, it throws an error.

I have to try and check by testing to fix this issue.

Kindly assign this to me

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by sadath2001** [comment]
I saw this bug, when i was trying to insert something from my localmachine.

**Comment by AlfiyaSiddique** [comment]
@sadath2001 does this issue still exists?
Not able to repro it on prod, it's working fine

**Comment by sadath2001** [comment]
@sadath2001 , yes, it does, only when we start fresh, i.e there are no existing recipes at all in the application. In which case, i will point to  undefined.

**Comment by AlfiyaSiddique** [comment]
@sadath2001 I tried to repro this issue using a new account but it works fine.
Can you present some video to confirm this is a valid bug.

**Comment by sadath2001** [comment]
https://github.com/user-attachments/assets/8c6d6520-0748-42d5-863a-b20e5b9b0e91


Its no longer an issue, since i applied the fix to this in the recipie validation PR. so i believe this can be closed.

**Comment by AlfiyaSiddique** [comment]
Okay then closing this issue.
