### ISSUE TITLE
FEATURE: Adding A F.A.Q.

### ISSUE THREAD

**Issue by Mandy1200** [AlfiyaSiddique/TastyTrails#113]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Adding F.A.Q. , for more user freindly and user experience 

### Component

main page/body of the website

### It should be implemented because

For the better user interface and experience , and more reach to the website easily

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@Mandy1200 What content will you add in FAQ?

**Comment by Mandy1200** [comment]
like who can use Tasty trails , what recipes can i find , can i save my recipes or many more .

Elsewhere you can also suggest me some F.A.Q. so can add according to it .

**Comment by AlfiyaSiddique** [comment]
@Mandy1200 This content does not require this web app or have any applications so closing this issue.
Thanks for showing interest.
