### ISSUE TITLE
FEATURE: Adding A Dark/Light Mode Toggle Button

### ISSUE THREAD

**Issue by Mandy1200** [AlfiyaSiddique/TastyTrails#115]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

I will Add a Dark/Light Mode Toggle Button 

Samples

![Screenshot (60)](https://github.com/user-attachments/assets/9ca64b7d-1684-4823-88b1-fecc1cf6d737)
![Screenshot (61)](https://github.com/user-attachments/assets/488c23ca-5208-438d-98a4-74be05bed5ca)

### Component

On the Top Right of the navbar , before the login button

### It should be implemented because

For Better User interface and user experience 

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@Mandy1200 there is no dark ligh feature in the site yet, through this issue are you going to build the full feature or just add the toggle button?

**Comment by Mandy1200** [comment]
I will Add The Both The Toggle Button And The Feature Also

**Comment by Dhruv-Gaba** [comment]
@AlfiyaSiddique I will add the complete feature. please assign this issue to me.

**Comment by AlfiyaSiddique** [comment]
@Mandy1200 just noticed that there is already an issue regarding this. So can't accept it. Closing this issue as it's a duplicate.

**Comment by AlfiyaSiddique** [comment]
Duplicate issue #57
