### ISSUE TITLE
FEATURE: Adding a ChatBot where an user can type some ingredients and it will give the recipe including that ingredients.

### ISSUE THREAD

**Issue by sanikaNB** [AlfiyaSiddique/TastyTrails#117]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

I wish to add a chatbot where a user can enter the ingredients they have and it will suggest/generate the recipe including that ingredients. Here i will be using react and openAI GPT to create an AI-powered Recipe Generator.

### Component

I would like to create this on a different page. I will include a one more element in navbar as recipe suggestions and when clicked it will redirect to this page.

### It should be implemented because

As it would be very feasible for user to get the recipe based on the ingredient they have . 

### Would you like to work on this issue?

yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
Nice Feature Suggestion @sanikaNB 
Please go ahaed, do implement it well

**Comment by govindumeesala** [comment]
@AlfiyaSiddique  can I work on this

**Comment by AlfiyaSiddique** [comment]
@sanikaNB any updates?

**Comment by Sawan-Kushwah** [comment]
@AlfiyaSiddique can I work on this please I can do it till tomorrow!! Please assign me

**Comment by AlfiyaSiddique** [comment]
@govindumeesala are you interested in working on this issue, also the deadline is 2 days after the issue gets assigned.
@Sawan-Kushwah as we follow a first come first assign policy. I have to ask the next contributor in the queue if no response found please tag me again it will get assigned to you.

**Comment by govindumeesala** [comment]
Yess , I would like to work on it

**Comment by AlfiyaSiddique** [comment]
@govindumeesala go ahead please implement it next 2 days

**Comment by govindumeesala** [comment]
ok
