### ISSUE TITLE
BUG: Password and Confirm Password Mismatch and Missing Visibility Toggle

### ISSUE THREAD

**Issue by faiz66388** [AlfiyaSiddique/TastyTrails#119]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe your issue

There is an issue with the password and confirm password fields where, even if the inputs are identical, the validation sometimes fails to recognize the match. Additionally, while the password field has a visibility toggle feature, the confirm password field does not, which could hinder the user experience.
![image](https://github.com/user-attachments/assets/ed6f72f0-964c-48d6-a7b9-ca85cde67e79)

### Steps to reproduce

1.Open the SignUp page.
2.Fill in all required fields, including the password and confirm password fields, with the same password.
3.Click on the "Sign Up" button.

### What was the expected result?

The password and confirm password fields should match correctly and allow form submission when the inputs are identical.
Both password and confirm password fields should have visibility toggle functionality to allow the user to see what they are typing.

### Proposed solution

The issue may arise from incorrect state handling or form validation logic. Here are potential fixes that can be implemented:

Ensure Synchronous State Updates: Verify that the state for both password and confirm password fields is updated synchronously before the comparison occurs. React’s state updates may not always happen immediately, so ensure the latest values are being compared.

Debounce Input Changes: Introduce debouncing for input fields to prevent rapid state updates that could cause mismatches between the two fields.

Adjust Validation Logic: Ensure that the password matching validation logic is executed only when both fields have been fully populated. The validation function should compare the two fields after the user finishes typing, such as when the form is submitted.

Form Validation Libraries: Consider using a form validation library like Formik or React Hook Form for more robust and efficient form state management and validation.

Implement Password Visibility for Confirm Password: The "Password" field has a toggle for visibility, but "Confirm Password" currently does not. To maintain consistency and improve user experience, I propose adding password visibility toggle to the "Confirm Password" field as well.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by Rahulagg13** [comment]
hey can you assign this issue to me?

**Comment by sadath2001** [comment]
I feel you must have had a space in your confirm password. works perfectly fine for me

**Comment by AlfiyaSiddique** [comment]
@faiz66388 this works perfectly fine on production and not an issue.
You must have space in your confirm password.
Also we do not need the visibility feature for confirm password as it is already there for password field
Thanks for showing interest
