### ISSUE TITLE
Make Navbar Sticky

### ISSUE THREAD

**Issue by saras-69** [AlfiyaSiddique/TastyTrails#12]
Description:
I would like to implement a sticky navbar for the application. This feature will keep the navbar visible at the top of the page as users scroll down, enhancing navigation and user experience.

Proposed Solution:

Use CSS to set the navbar's position to "sticky" or "fixed" at the top of the viewport.
Ensure that the navbar remains responsive and does not overlap with other page content.
Test the functionality across different screen sizes and browsers for compatibility.
Benefits:

Improves usability by providing constant access to navigation options.
Enhances the overall user experience by reducing scrolling time to access the navbar.

**Comment by saras-69** [comment]
"Please assign this issue to me so that I can work on it."

**Comment by shubhagarwal1** [comment]
the footer also needs to be fixed 
@AlfiyaSiddique  please allow me to fix it

**Comment by AlfiyaSiddique** [comment]
@shubhagarwal1  Please open a seperate issue for footer and describe what will you improve in it.

**Comment by AlfiyaSiddique** [comment]
Hi @saras-69 
Welcome to TastyTrails!🎉

Thanks for opening this issue.
Please Go ahead with the sticky navbar feature.
Also, make sure the navbar is not sticky in the first 100vh and if the first 100vh of the website is scrolled then it appears sticky on top. Let me know if you face any issue.

**Comment by saras-69** [comment]
sure

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 Please open a seperate issue for footer and describe what will you improve in it.

have raise a saperate issue please review
