### ISSUE TITLE
BUG: First name and lastname can contain letters too?

### ISSUE THREAD

**Issue by sadath2001** [AlfiyaSiddique/TastyTrails#120]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe your issue

I found an issue where the first name and last name field, even if having letters or special characters in them, gets accepted.

### Steps to reproduce

1. goto signup
2. enter your fname and lname with numbers and special characres
3. 
![image](https://github.com/user-attachments/assets/a5621601-a243-442a-afb5-0612ac04e7e2)
![image](https://github.com/user-attachments/assets/8812f261-8e28-40d3-851e-ea4bde967e68)

it still gets signed up without any errors

### What was the expected result?

I should show a validation error

### Proposed solution

Fix the validations accordingly to show an error.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@sadath2001 go ahaed
