### ISSUE TITLE
BUG: Footer should be sticky

### ISSUE THREAD

**Issue by sadath2001** [AlfiyaSiddique/TastyTrails#121]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe your issue

I could see that, in a few pages, when i go to it, and there is no content in there, the footer comes up to the top, whereas it shouldnt be the case.

### Steps to reproduce

1. Goto notifications
2. You could see as below
![image](https://github.com/user-attachments/assets/ee363994-03fc-4715-ad32-6a49a781f5a4)
3. Same is with main pages too

![image](https://github.com/user-attachments/assets/a31755b9-47fd-4fc9-9b5d-5042efacbb68)

### What was the expected result?

The footer should be fixed to a static place, in this case to the bottom

### Proposed solution

Making the footer sticky by changing a few properties in CSS

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by albinsabu2023** [comment]
hey bro i can work on this. can you asssign it to me

**Comment by AlfiyaSiddique** [comment]
@sadath2001 please go ahead

**Comment by AlfiyaSiddique** [comment]
@albinsabu2023 issues are assigned on first come first serve basis and do not open a PR without getting assigned to an issue . This can result in loss of work. You can find other issues which are unassigned or you can open your own issues which you think need improvement.
