### ISSUE TITLE
ENHANCEMENT: Adding a display page when no recipies are there in profile

### ISSUE THREAD

**Issue by sadath2001** [AlfiyaSiddique/TastyTrails#122]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

I would like to add a display message or a page in myprofile that shows "nothing here as of now" and some random quote about cooking each time whenver there is nothing in the users profile
![image](https://github.com/user-attachments/assets/b7b40a3a-ab6c-4244-aa0f-7b59b61347ff)

### Component

/user (profile)

### It should be implemented because

It would give a good impression and i feel itll make the site look cool rather than boring blank page.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@sadath this problem is already in development
