### ISSUE TITLE
ENHANCEMENT: Adding a 404 page

### ISSUE THREAD

**Issue by sadath2001** [AlfiyaSiddique/TastyTrails#123]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

I see that there is no 404 page that redirects when user types in a wrong URL
eg:
![image](https://github.com/user-attachments/assets/a8b835da-c1dd-4606-9c00-3e6cb663aea8)

### Component

Applies to the whole website

### It should be implemented because

Its always better to show a good 404 page in case the user types in the wrong URL
My idea:
![image](https://github.com/user-attachments/assets/34fb12da-2977-4dee-86cf-108efb956ca9)

ill try making a page with animations which match the current theme

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@sadath2001 go ahaed
But make sure to share the design and layout of 404 page before submitting the PR

**Comment by Pariyul** [comment]
hey i want to contribute in this , can you please assign it to me under hacktober fest and ggsoc-ext.

**Comment by sadath2001** [comment]
Hi Alfiya, sure, will share the designs this weekend

**Comment by sadath2001** [comment]
Hi @AlfiyaSiddique , any improvements?

Normal screen size:

![image](https://github.com/user-attachments/assets/4718468f-c359-4cd7-94a4-07eb045e51c7)

when resized:
![image](https://github.com/user-attachments/assets/ecc3f1c0-6d46-47d7-b04d-22ce38d99f23)

**Comment by AlfiyaSiddique** [comment]
@sadath2001 Some changes:
The image is repeated so can you please change it:
Use something like an empty plate with a spoon and fork if possible or use any other image but not repeat the previous one.
When resizing after 404 we could not find the page text put the image and then add the other text and homepage button.
Let me know if have nay doubt.

**Comment by sadath2001** [comment]
Sure I will make the changes

**Comment by sadath2001** [comment]
![image](https://github.com/user-attachments/assets/0cb04a7f-4363-44a2-a033-73c99e5b98c6)
![image](https://github.com/user-attachments/assets/1a93a570-360f-41c9-9575-8acaa060401d)

hi @AlfiyaSiddique  kindly review

**Comment by AlfiyaSiddique** [comment]
Looks good!
If I am not wrong, from the picture, it seems there are two buttons for Back to homepage in mobile view. You can remove the top one and it's good to go.

**Comment by sadath2001** [comment]
Sure I'll fix it and raise a PR. Thanks
