### ISSUE TITLE
BUG: Reference error in signup page

### ISSUE THREAD

**Issue by sadath2001** [AlfiyaSiddique/TastyTrails#128]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe your issue

I could see that there is a reference error in signup page:
![image](https://github.com/user-attachments/assets/97d69bf3-9a40-4b73-b5a6-aa405287b3ce)

### Steps to reproduce

1. Goto signup
2. Console.log when you are entering password/confirm password

### What was the expected result?

The error shouldnt have had been showing

### Proposed solution

Might be because of some unhandled stuff, or reference conflict. ill have to check, but ill fix it asap

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@sadath2001 go ahaed
