### ISSUE TITLE
Implement Scroll-to-Top Button

### ISSUE THREAD

**Issue by samyak-aditya** [AlfiyaSiddique/TastyTrails#13]
I would like to enhance the user experience by adding a "Back to Top" button on the page. This button will allow users to easily navigate back to the top of the page

Please Assign me this feature @AlfiyaSiddique  with the tag "gssoc-ext" and "level"

**Comment by AlfiyaSiddique** [comment]
Hi @samyak-aditya 
Welcome To TastyTrails!🎉

Thanks for opening this issue.
Please Go ahead .

**Comment by samyak-aditya** [comment]
Hey @AlfiyaSiddique I have raised the PR for this Task 
also add the level label
