### ISSUE TITLE
ENHANCEMENT: Adding validation to recipie

### ISSUE THREAD

**Issue by sadath2001** [AlfiyaSiddique/TastyTrails#135]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

Hi ,
I would like to add a validation check to delete the recipie. i.e if the image doesnt get deleted, the recipie shouldnt get deleted either as mentioned in #

### Component

/Recipie deletion (in users tab)

### It should be implemented because

it will add better error handling functionality

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
Okay @sadath2001, make sure this fixes the bug that is causing the files not to delete from GitHub ImageDatabase Repo
