### ISSUE TITLE
BUG: Footer should always at bottom

### ISSUE THREAD

**Issue by tarunkumar2005** [AlfiyaSiddique/TastyTrails#136]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe your issue

![image](https://github.com/user-attachments/assets/3fec661a-f2b2-449d-9f56-6ba2617fd7f8)

Here you can see the footer is at the top which shouldn't be there okay because even if there are not recipies the footer should always be at bottom.

### Steps to reproduce

..

### What was the expected result?

Footer always at bottom

### Proposed solution

Assign this to under gssoc 2024 ext and hacktoberfest @sadath2001 i will work on this issue.

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by sadath2001** [comment]
Okay, you can..but it should be assigned to by the project admin.

**Comment by tarunkumar2005** [comment]
@sadath2001 Can you ask project admin to assign it or mention the project admin here to assign this issue to me i don't know who is admin as you have merged the latest PR so  i thought you are the admin

**Comment by sadath2001** [comment]
Hi @tarunkumar2005 , i apologise, i didn't see that there was an existing issue already. I don't think that this can be assigned to you.

You can raise a new issue
Ps: the project admin is @AlfiyaSiddique .

**Comment by AlfiyaSiddique** [comment]
@tarunkumar2005  there is an existing issue to this #121  opened by @sadath2001 
So this is the duplicate issue.
@sadath2001 are you working on #121 or do you want it to be assigned to @tarunkumar2005, the above conversation seems confusing so please clarify!

**Comment by sadath2001** [comment]
Hey @AlfiyaSiddique , no I'll be working on the issue.

**Comment by AlfiyaSiddique** [comment]
@tarunkumar2005 thanks for showing interest but this issue is already taken.
You are free to open new issues for yourself and if they are valid they will get assigned to you. All the best!
