### ISSUE TITLE
ENHANCEMENT: adding a chatbot

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [AlfiyaSiddique/TastyTrails#137]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

ill add a chatbot fine tuned for this website.

### Component

this will be interactive.

### It should be implemented because

this can help the user find answers to questions he doesnt understand.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by T-Rahul-prabhu-38** [comment]
@AlfiyaSiddique can you please assign me this task.

**Comment by AlfiyaSiddique** [comment]
@T-Rahul-prabhu-38 a chatbot issue is already in development. #117
