### ISSUE TITLE
Automated Greeting Workflow

### ISSUE THREAD

**Issue by shubhagarwal1** [AlfiyaSiddique/TastyTrails#14]
I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository. The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.
Hey @AlfiyaSiddique, please allow to do this task.

**Comment by AlfiyaSiddique** [comment]
Hi @shubhagarwal1 
Welcome To TastyTrails!

Thanks a lot for opening this issue! We needed this.
Please Go Ahead.
If can you add more automated workflows by opening different issues it will be great.

**Comment by shubhagarwal1** [comment]
> Hi @shubhagarwal1 Welcome To TastyTrails!
> 
> Thanks a lot for opening this issue! We needed this. Please Go Ahead. If can you add more automated workflows by opening different issues it will be great.

@AlfiyaSiddique thank you for the opportunity, can you please give me some details for more automated workflows
i can present first draft for automated workflow on raising issue and PR then i can move forward adding more, sounds good to you?

**Comment by AlfiyaSiddique** [comment]
Yes sounds good.👍🏻
More Automated workflows can include, 
Template for issues:
Template for PRs etc.

**Comment by shubhagarwal1** [comment]
> Yes sounds good.👍🏻 More Automated workflows can include, Template for issues: Template for PRs etc.

can you please merge this PR i will start working on the more auomated workflow then
