### ISSUE TITLE
ENHANCEMENT: Add animations to dishes Card components | improving UI ⭐

### ISSUE THREAD

**Issue by akanksha1055** [AlfiyaSiddique/TastyTrails#144]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

I will add smooth slight 3d pop up transition to the dishes display As currently it looks plain and less interactive 
Please assign me this issue Under :
GSSoc 
Hacktober if possible

### Component

https://delightful-daifuku-a9f6ea.netlify.app/   
![image](https://github.com/user-attachments/assets/86afb869-b296-41d6-addd-6a36b6ea256e)

### It should be implemented because

To make the site more fun and interactive and improve user Experience

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@akanksha1055 can you give a reference what kind of animation will you add?

**Comment by nataliakrein** [comment]
Could you please assign me this issue? Thanks

**Comment by AlfiyaSiddique** [comment]
@akanksha1055 not needed
