### ISSUE TITLE
BUG:  Username Uniqueness Issue

### ISSUE THREAD

**Issue by MohammedMusharraf11** [AlfiyaSiddique/TastyTrails#146]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe your issue

When creating an account on the website, the username uniqueness validation can be bypassed by adding an extra space at the end of the username. This allows users to register multiple accounts with the same username but with an additional space.

### Steps to reproduce

- Create an account with any email and username (e.g., "github").
- Attempt to create another account with a different email but the same username ("github").
   - **Expected Result**: A message like "username already taken."
   - **Actual Result**: A React toast message correctly states "username already taken."
- Now, try creating an account with a different email but with an extra space in the username (e.g., "github ").
    - **Expected Result**: The username uniqueness check should fail.
     - **Actual Result**: The account is created successfully with "github " as the username.

### What was the expected result?

The system should treat usernames as case-insensitive and should also strip leading/trailing spaces when validating uniqueness.

### Proposed solution

Trim Whitespaces on Username Input: Ensure that any leading or trailing whitespaces are removed from the username input before performing the uniqueness validation and before saving it to the database.
We can use this -> `String.prototype.trim()`

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@mohdazam0786 this task is already taken

**Comment by mohdazam0786** [comment]
I want to do my first contribution in open source journey that's why I asked you

**Comment by AlfiyaSiddique** [comment]
yes, you are free to open new valid issues for yourself

**Comment by MohammedMusharraf11** [comment]
> @MohammedMusharraf11 go ahead and fix this bug

I have created a PR 
Please review and merge it
@AlfiyaSiddique
