### ISSUE TITLE
FEATURE:  Implement Recipe Sharing Feature

### ISSUE THREAD

**Issue by 23WH1A0507** [AlfiyaSiddique/TastyTrails#152]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

I propose adding a Recipe Sharing Feature that allows users to share their favorite recipes directly on social media platforms such as Facebook, Twitter, and Pinterest.

### Component

This feature will be added to the existing recipe detail page, specifically at the URI: /recipes/:id.

### It should be implemented because

->Enhance user engagement by encouraging users to showcase their favorite recipes.
->Increase visibility for the application as recipes are shared across social media platforms.
->Foster a sense of community, allowing users to connect over shared culinary interests.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@23WH1A0507 go ahead assigning to you, do add your approach here How will you do this.

**Comment by raj-adi00** [comment]
There has been no response. Can i work on this. Please assign under hacktoberfest-accepted and gssoc-24 extd

**Comment by AlfiyaSiddique** [comment]
@23WH1A0507 any progress on this?

**Comment by raj-adi00** [comment]
@AlfiyaSiddique assign it to me.

**Comment by AlfiyaSiddique** [comment]
@raj-adi00 assigned to you please implement it soon

**Comment by raj-adi00** [comment]
@AlfiyaSiddique i have updated share option. Please let me know if you want anything to be changed
