### ISSUE TITLE
FEATURE: Adding a pull request template

### ISSUE THREAD

**Issue by sadath2001** [AlfiyaSiddique/TastyTrails#155]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Hi would like to add a standard template for pull requests

### Component

github

### It should be implemented because

makes it a standardized process by adding fields such as pictures, demonstrations etc so that itll avoid back and forth comms

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@sadath2001 go ahead. In the template also make the gssoc and hacktoberfest-accepted label to add in all PRs automatically as it happens with the issue.

**Comment by AlfiyaSiddique** [comment]
Also @sadath2001 I noticed you have already been assigned to some main issues like OAuth and Chat functionality for a long time and there are no updates on them as you continuously keep working with other issues. Those features are more important so please do them on priority. If you are too occupied then please let me assign them to other contributors. Those features need to be completed within this event.

**Comment by sadath2001** [comment]
Hi @AlfiyaSiddique , i apologise, I'll keep those two on priority and try to complete them off at the earliest.

Thank you for bringing this to my attention.

**Comment by sadath2001** [comment]
hi @AlfiyaSiddique , kindly review:
![image](https://github.com/user-attachments/assets/cd42c43d-f3a3-44ee-be54-cf5f818778c8)
![image](https://github.com/user-attachments/assets/df718202-65d4-477d-bf77-4a1526c303ab)

**Comment by AlfiyaSiddique** [comment]
Looks good @sadath2001, just if we can remove the space below each section heading. It seems like too mush space.

**Comment by sadath2001** [comment]
Sure, ill change it and will raise a PR
