### ISSUE TITLE
FEATURE: Adding license and security policy

### ISSUE THREAD

**Issue by sadath2001** [AlfiyaSiddique/TastyTrails#156]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

I would like to work on adding these templates

### Component

github

### It should be implemented because

its a good practice, ill send over the screenshots of the template before raising a PR.
Kindly assign this to me

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@sadath2001 did not get this issue, please describe it well.

**Comment by sadath2001** [comment]
hi @AlfiyaSiddique , i meant this,
![image](https://github.com/user-attachments/assets/e04ab623-8d04-49ba-b962-19fcecdfe3aa)
https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository,

its basically for reporting security vulnerabilities

**Comment by AlfiyaSiddique** [comment]
@sadath2001 the license can be auto-generated so I have added it now, you can work on the security policy doc.

**Comment by AlfiyaSiddique** [comment]
Write it well & descriptive

**Comment by sadath2001** [comment]
hi @AlfiyaSiddique , kindly review once:
![image](https://github.com/user-attachments/assets/79e79c95-9bd0-44ce-82f8-1aac10d31b21)

**Comment by AlfiyaSiddique** [comment]
@sadath2001 looks fine. Can raise PR
