### ISSUE TITLE
BUG: Updating the recipie makes URL mismatch

### ISSUE THREAD

**Issue by sadath2001** [AlfiyaSiddique/TastyTrails#157]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe your issue

hi,

i found a bug, here is the video

https://github.com/user-attachments/assets/e520117c-5c4a-430b-9032-45fa41f9db27

### Steps to reproduce

1. goto profile
2. update the recipies
3. watch the url

### What was the expected result?

instead of returning undefined, it should be displaying the userid there

### Proposed solution

i should find the error, might be due to some reference mismatch

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@sadath2001 go ahead.
Also, one thing to mention.
Because of the change made with your sticky footer PR of yours, there is a change in the margin of the update button.
Can you please fix it in the same PR that you will raise to fix this bug?

**Comment by sadath2001** [comment]
Hi , sure let me take a look

**Comment by AlfiyaSiddique** [comment]
Also please make the footer sticky only if the page size is less than the screen size. Otherwise, it's spoiling the look of the Landing page First Screen.

**Comment by sadath2001** [comment]
hi, sure will change it.
