### ISSUE TITLE
Issue Title: "Enhance Footer Section and Scroll to Top Feature"

### ISSUE THREAD

**Issue by AswaniBolisetti** [AlfiyaSiddique/TastyTrails#158]
@AlfiyaSiddique 
Issue Description: I would like to enhance the footer section to look it more attractive and to make it as relevant according to the website and also I want to enhance the scroll to top feature also, please assign me this issue under level2, gssoc-ext, hacktoberfest-accepted.

**Comment by AlfiyaSiddique** [comment]
@AswaniBolisetti  enhancement in the footer is already under development.
Also, any change related to design needs a design proposal or reference first.

**Comment by AswaniBolisetti** [comment]
Thank you
