### ISSUE TITLE
ENHANCEMENT: Signup Form with confirm Password Visibility Toggle

### ISSUE THREAD

**Issue by mohdazam0786** [AlfiyaSiddique/TastyTrails#163]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

**### Password Visibility Toggle:**
Users can **easily toggle** the visibility of their password and confirm password fields with eye/eye-slash icons, which improves usability, especially on any devices or when typing complex passwords.

https://github.com/user-attachments/assets/b339fa04-1286-4e2f-b901-d66d09766de4

### Component

![image](https://github.com/user-attachments/assets/723ffed4-6fac-4ca9-aa63-fb7eb2faad01)

https://github.com/user-attachments/assets/995f9e2d-2139-474a-8d9a-054f28aac0e3

### It should be implemented because

Users can easily switch between hiding and showing their password, which reduces frustration during account creation.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by mohdazam0786** [comment]
@AlfiyaSiddique please assign this task to me

**Comment by AlfiyaSiddique** [comment]
@mohdazam0786 this feature is not needed.
The confirm password compares the value with the password field to let them know if the right password has been entered or not.
Thanks for showing interest.
