### ISSUE TITLE
FEATURE: Add Google Authentication for Login and Signup

### ISSUE THREAD

**Issue by rudrapratap63** [AlfiyaSiddique/TastyTrails#168]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

We need to enhance the user experience by adding Google authentication functionality to our login and signup pages. This will allow users to sign in or sign up using their Google accounts, making the process quicker and more convenient.

### Component

/signup 
/login

### It should be implemented because

- Users can successfully sign in or sign up using their Google accounts.
- The "Continue with Google" button is clearly visible and functional on both pages.
- The UI enhancements are implemented, making the pages more user-friendly.

![Screenshot 2024-10-11 135022](https://github.com/user-attachments/assets/6d13cc89-409e-4f51-8706-46a6026ccdf7)
![Screenshot 2024-10-11 135159](https://github.com/user-attachments/assets/95676d7a-2473-49af-a31b-8853b9bf9a6d)

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by rudrapratap63** [comment]
@AlfiyaSiddique Please assign this issue to me i will also enhance the UI of login and sign up page

**Comment by AlfiyaSiddique** [comment]
@rudrapratap63  any changes to the design of the website need a design proposal or reference first. So if you have any better design ideas please share them in the comment

**Comment by AlfiyaSiddique** [comment]
@rudrapratap63 this is already under development in issue #8
