### ISSUE TITLE
FEATURE: Implement food ordering backend

### ISSUE THREAD

**Issue by haseebzaki-07** [AlfiyaSiddique/TastyTrails#169]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

I want to add food ordering handlers and schema for the backend that associates a user with an order

### Component

/backend/controllers/order

### It should be implemented because

It is important feature for a website like this and should be properly implemented 

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@haseebzaki-07 this is a food recipe site and not a food ordering site. Because this feature seems not relevant I am closing this issue. Can comment if you have to clarify anything
