### ISSUE TITLE
ENHANCEMENT: signup/login

### ISSUE THREAD

**Issue by MisbahAnsar** [AlfiyaSiddique/TastyTrails#170]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

- when clicked on signup page, other page should be opened instead of there itself, the navbar still stays there which makes the ui for signup page get bad for ui, same goes for login page as well
- user shouldn't see the navbar or logic button on the top of the page when he/she is on signup page, the login button should be included in the singup page below   ------there r some images attached------

* i am ready to work on this, assign it to me 👍 

### Component

![image](https://github.com/user-attachments/assets/f2afcf62-ba31-4a16-82a3-f1bcfa69ad9e)
![Screenshot 2024-10-11 180811](https://github.com/user-attachments/assets/e43f73b7-2ba9-4515-ac92-aefef877d14c)

### It should be implemented because

a good user interaction is much needed for every websites !!

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@MisbahAnsar your bugs written in the description are not matching with the deployed site. Please provide a video to confirm that these are valid bugs.

**Comment by MisbahAnsar** [comment]
here, in this page the place where i am moving my pen, that shouldn't be there, attaching some photos for example

https://github.com/user-attachments/assets/b1156285-e0bb-45d0-a10e-74a09aecb3aa

signup image(can be like this) : 
![signup](https://github.com/user-attachments/assets/09ec0f9e-1941-41eb-b6f8-0c0e9f1a17b7)

**Comment by AlfiyaSiddique** [comment]
@MisbahAnsar.
we want the navbar to be visible even if the Signup and login page is shown we do not want to change the current layout.
Thanks for showing interest.
