### ISSUE TITLE
ENHANCEMENT: landing nd feature page

### ISSUE THREAD

**Issue by MisbahAnsar** [AlfiyaSiddique/TastyTrails#171]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

The space between the landing page and the feature page is more than needed, it can be more enhance

* i am ready to work on this issue 

### Component

![Screenshot 2024-10-11 181632](https://github.com/user-attachments/assets/f54669ad-9ce3-47bd-b2d2-ad6f8f6e9327)

### It should be implemented because

cause the scrolling is extra, nd user can think that there is no more pages nd leave the site 

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@MisbahAnsar please specify on which size and mobile model this issue is occuring

**Comment by MisbahAnsar** [comment]
iphone 13 pro, samsung galaxy s20, xiaomi M1 11i and many more, i've attached one video as well 👍 

https://github.com/user-attachments/assets/75673d90-bf91-4a21-b25c-3873d8e9bb8b

**Comment by AlfiyaSiddique** [comment]
@MisbahAnsar please go ahead and fix it. Assigning to you.
