### ISSUE TITLE
FEATURE: Adding a Contact us Form

### ISSUE THREAD

**Issue by ark0078** [AlfiyaSiddique/TastyTrails#172]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Want to add a Contact Us form

### Component

On the home page itself...at footer

### It should be implemented because

Cause then if any user wants to reach out to the owner,they can directly do so by clicking on the "Contact Us" feature

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by itznayan** [comment]
Please assign this issue to me.

**Comment by AlfiyaSiddique** [comment]
@ark we do not need a contact us form for the site currently.
Thanks for showing interest
