### ISSUE TITLE
FEATURE: Add sign in with google option

### ISSUE THREAD

**Issue by Kajalmehta29** [AlfiyaSiddique/TastyTrails#174]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

I want to add sign in with google option to make it more convenient.
Please assign this issue to me under gssoc-extd and hacktoberfest.

### Component

On the login/signup page i want to add on this feature.

### It should be implemented because

It will become user-friendly

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@Kajalmehta29 This is already under development in #8 
Thanks for showing interest.
