### ISSUE TITLE
ENHANCEMENT: adding more recipes

### ISSUE THREAD

**Issue by Bhumika-00** [AlfiyaSiddique/TastyTrails#176]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

I will add more dishes in order to fill up the page.

### Component

2 more flashcards of recipes will be added.

### It should be implemented because

Because we sholud tell about more delicasies.

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by Abhilash107** [comment]
I want to work on this.
Please assign it to me @AlfiyaSiddique.

**Comment by Bhumika-00** [comment]
I want to work on this issue please assign it to me

**Comment by AlfiyaSiddique** [comment]
@Bhumika-00 this is not an issue and instead a usecase of the website. So not a valid issue.
Thanks for showing interest.
