### ISSUE TITLE
ENHANCEMENT: Footer Alignment and Feedback Button Not Displayed Correctly

### ISSUE THREAD

**Issue by Priyanshu282003** [AlfiyaSiddique/TastyTrails#177]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

The footer on the website is not aligned properly, causing visual inconsistencies. Additionally, the "Feedback" button is partially cut off and not fully visible on the page, especially towards the bottom right corner of the page.

### Component

The footer content should be properly aligned and centered, providing a neat and visually appealing look.
The "Feedback" button should be fully visible and clickable, without being cut off by other elements.
![image](https://github.com/user-attachments/assets/9d7826e9-62eb-4cf8-a9bc-8fae50a54231)

### It should be implemented because

A well-aligned footer ensures a polished look and prevents confusion. Accessible feedback buttons improve user interaction and make it easier to gather insights.
Proper alignment is crucial for users on different devices, ensuring the footer is functional on smaller screens. It enhances responsiveness and keeps all elements easily accessible.
 Key links and CTAs like the "Feedback" button are more visible with correct alignment. This boosts user engagement and interaction with important features.
 A visible "Feedback" button ensures users can easily provide insights. Proper alignment guarantees that feedback collection is seamless on all devices.

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by Priyanshu282003** [comment]
Could you please assign the level label?

**Comment by sadath2001** [comment]
hi, there is an existing issue regarding this.

**Comment by AlfiyaSiddique** [comment]
@Priyanshu282003 This issue is under development and will be solved within a PR of another issue.
Thanks for showing interest.
