### ISSUE TITLE
ENHANCEMENT:  Landing.jsx into Separate Components for Better Code Maintainability

### ISSUE THREAD

**Issue by MisbahAnsar** [AlfiyaSiddique/TastyTrails#178]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

Currently, the Landing.jsx file contains multiple sections including the Navbar, Landing Page, Features, About Us, and Footer. To improve the code’s readability, maintainability, and scalability, we should refactor these sections into individual components. This will allow each part of the page to be reused independently and make future updates or changes easier to implement.

### Component

to improve the maintability i.e; writing the components of each sections, instead of writing all the sections in one page:
eg:
Landing.jsx currently contains: navbar, hero,feature,aboutus,footer

instead of this, this will be more usefull for better understanding:
Landing.jsx(main file):
 -   navbar.jsx
 -   hero.jsx
 -   feaute.jsx
 -  aboutus.jsx
 -  footer.jsx

### It should be implemented because

to improve maintainability, scalability, and reusability of the code by breaking down a large, monolithic file into smaller, focused components

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [x] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@MisbahAnsar Since these sections are not reusable no need to add them in separate components.
Thanks for showing interest
