### ISSUE TITLE
FEATURE: Comment section for each recipe

### ISSUE THREAD

**Issue by saumy-sh** [AlfiyaSiddique/TastyTrails#182]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Enable users to comment on recipes and leave reviews or tips based on their cooking experience.

### Component

/recipe

### It should be implemented because

- Builds Trust and Credibility
- Improves Recipe Quality
- Enhances Community Engagement
- Helps New Users

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@saumy-sh great idea!
Please go ahead. I hope you will implement backed and frontend both.

**Comment by saumy-sh** [comment]
I think I would need access to your mongodb database. Can you provide that please?

**Comment by AlfiyaSiddique** [comment]
@saumy-sh you can work on your local database. Please see the readme to understand in detail about how to setup the project locally.

**Comment by saumy-sh** [comment]
Okay sure! I will look into it. Thanks

**Comment by AlfiyaSiddique** [comment]
Please comment if face any errors:)

**Comment by saumy-sh** [comment]
for running it on my local machine I changed .env files, so while making pr can i keep those changes?

**Comment by AlfiyaSiddique** [comment]
Yes please keep it, if need to remove I will comment on the PR code. But as of now, you can keep it.
