### ISSUE TITLE
FEATURE: Want to add privacy policy to your website

### ISSUE THREAD

**Issue by ark0078** [AlfiyaSiddique/TastyTrails#183]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Privacy Policy is required for customers to have a regular visit on your website

### Component

At the footer of homepage..am gonna send you the html portion and you'll just add it

### It should be implemented because

Because it's important for a website to have a large no of customers so that customers feel safe when they input their sensitive information

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@ark0078 what will you add to the privacy policy content and what will the layout and design of this , please specify in detail

**Comment by Sarthakkashyapp** [comment]
Key Sections Included in the Privacy Policy:

Introduction

Overview of our commitment to user privacy.
Information We Collect

Personal Information: Details like name, email address, and profile information collected during registration and user interactions.
Non-Personal Information: Usage data, browsing patterns, and cookie information.
How We Use Your Information

Providing and personalizing services.
Communicating updates and promotional materials.
Improving website functionality and user experience.
Ensuring security and preventing fraudulent activities.
Data Sharing and Disclosure

Sharing with trusted third-party service providers for site operations and analytics.
Legal obligations for data disclosure when required by law.
Information about potential data transfers in case of business changes like mergers or acquisitions.
Cookies and Tracking Technologies

Explanation of cookie usage to enhance user experience and analyze site traffic.
Options for users to manage or opt-out of cookies through their browser settings.
Data Security

Measures implemented to protect user data from unauthorized access, breaches, or loss.
Your Rights

Information on user rights to access, modify, or delete their personal data.
Instructions on how users can exercise these rights by contacting us.
Changes to This Privacy Policy

Notification that the policy may be updated periodically.
Encouragement for users to review the policy regularly.
Contact Us

Contact details for any privacy-related inquiries or concerns.
Implementation Details:

Dedicated Page: The Privacy Policy is accessible via a link in the website's footer for easy user access.
Responsive Design: Styled using TailwindCSS to ensure it aligns with the website’s overall aesthetic and is mobile-friendly.
Legal Compliance: The policy is structured to comply with relevant regulations such as GDPR and CCPA, ensuring we meet necessary legal requirements.
Please review the Privacy Policy page at your earliest convenience and let me know if there are any adjustments or additional information you would like to include.

Thank you for your attention to this important aspect of our project.
@AlfiyaSiddique Please look into this and let me know what are your expectations from this.

**Comment by AlfiyaSiddique** [comment]
@Sarthakkashyapp Do not add the cookie part and trusted third-party section as this is not relevant for our site. We only collect data for registration and feedback messages. There is no cookie implemented as of now other than session functionality I guess.

We also do not have the feature to delete user accounts as of now. 
So tell me in short what points we can add then you have to draft the contents for those points if accepted.
And then propose a policy page design after this the issue will be assigned to you and you can start implementing.
Let me know if you are up for this.

**Comment by Sarthakkashyapp** [comment]
> @Sarthakkashyapp Do not add the cookie part and trusted third-party section as this is not relevant for our site. We only collect data for registration and feedback messages. There is no cookie implemented as of now other than session functionality I guess.
> 
> We also do not have the feature to delete user accounts as of now. So tell me in short what points we can add then you have to draft the contents for those points if accepted. And then propose a policy page design after this the issue will be assigned to you and you can start implementing. Let me know if you are up for this.

Sure give me some time to look into this and I'll then finalise what I can do.

**Comment by ark0078** [comment]
@AlfiyaSiddique since @Sarthakkashyapp wants to take up this issue..give him....But I can solve this..actually just now checked the issue and I don't want to break someone's heart by snatching this...I've created the issue and other will solve it...seems nice to me....     @AlfiyaSiddique give him...thank you

**Comment by ark0078** [comment]
i mean just now checked my mail

**Comment by Sarthakkashyapp** [comment]
> i mean just now checked my mail

@ark0078 Its upto @AlfiyaSiddique to whom she'll assign and also I am not snatching it from you I just saw it and commented for this.

**Comment by ark0078** [comment]
@Sarthakkashyapp one suggestion from my end...always think an issue of yourself...if you can't think,you won't be a good person ever...anyways,All the best!!Thank you...but try to think an issue of yourself...don't snatch it..if you see an issue..don't comment there also cause everyone is busy with there work..none is free to check mails all the day long...hope you got me!!!Think

**Comment by ark0078** [comment]
> > i mean just now checked my mail
> 
> @ark0078 Its upto @AlfiyaSiddique to whom she'll assign and also I am not snatching it from you I just saw it and commented for this.

simply an excuse!!take it...not needed

**Comment by Sarthakkashyapp** [comment]
> > > i mean just now checked my mail
> > 
> > 
> > @ark0078 Its upto @AlfiyaSiddique to whom she'll assign and also I am not snatching it from you I just saw it and commented for this.
> 
> simply an excuse!!take it...not need

> > > i mean just now checked my mail
> > 
> > 
> > @ark0078 Its upto @AlfiyaSiddique to whom she'll assign and also I am not snatching it from you I just saw it and commented for this.
> 
> simply an excuse!!take it...not needed

As your wish

**Comment by Sarthakkashyapp** [comment]
> @Sarthakkashyapp one suggestion from my end...always think an issue of yourself...if you can't think,you won't be a good person ever...anyways,All the best!!Thank you...but try to think an issue of yourself...don't snatch it..if you see an issue..don't comment there also cause everyone is busy with there work..none is free to check mails all the day long...hope you got me!!!Think

Fyi I have also created a issue for myself and also get assigned and checking emails is part of my work also it shows activeness everyone is not too busy its just about priorities 😌

**Comment by ark0078** [comment]
@Sarthakkashyapp ofc....it's about priorities...so dear,kindly do check my profile,I'm not contributing in one project...I've been assigned many projects where I need to fix bugs or need to perform feature enhancement..do check once,you'll understand it...thank you..God bless you...I don't have time for this vague argument!!lmao...take care

**Comment by Sarthakkashyapp** [comment]
> @Sarthakkashyapp ofc....it's about priorities...so dear,kindly do check my profile,I'm not contributing in one project...I've been assigned many projects where I need to fix bugs or need to perform feature enhancement..do check once,you'll understand it...thank you..God bless you...I don't have time for this vague argument!!lmao...take care

You don't have time but still commenting 👍🏻

**Comment by ark0078** [comment]
So silly!!!  @Sarthakkashyapp you better think an issue!!!lmfao...

**Comment by Sarthakkashyapp** [comment]
> So silly!!!  @Sarthakkashyapp you better think an issue!!!lmfao...

The only pro contributor right here 🤣

**Comment by ark0078** [comment]
> > So silly!!!  @Sarthakkashyapp you better think an issue!!!lmfao...
> 
> The only pro contributor right here 🤣

@Sarthakkashyapp btw,you're right....lmao!!!

**Comment by AlfiyaSiddique** [comment]
@ark0078 I am So Sorry, While commenting I did not notice that this issue was opened by you.
I thought it was opened by @Sarthakkashyapp when saw his comment that's why I replied to the comment.
I want to clarify that the issues are assigned on first come first serve basis so this issue technically  belongs to @ak3264114 
I apologize again, this misunderstanding is due to me @ark0078 
@ark0078  please let me know if you are still up for this issue.

**Comment by Sarthakkashyapp** [comment]
@AlfiyaSiddique exactly it technically belongs to him and I am also telling him that but he is taking in a wrong way.

**Comment by Sarthakkashyapp** [comment]
@ark0078 go for it, I am not here to fight with you buddy it's just a misunderstanding peace out.

**Comment by ark0078** [comment]
@Sarthakkashyapp dear,take it....come on..no worries....don't worry buddy...why fighting with each other??Better we collaborate!

**Comment by ark0078** [comment]
handshake @Sarthakkashyapp

**Comment by AlfiyaSiddique** [comment]
I request both of you to not argue on this.
Let's solve this out.
@ark0078 please work on this as you have opened it, let me know your decision.
Due to dealing with so many PR and Issues, I did this mistake I am apologizing one more time, Please let me know @ark0078 if you are up for this or not.

**Comment by AlfiyaSiddique** [comment]
Anyway just inform me who is working on this issue

**Comment by Sarthakkashyapp** [comment]
> @AlfiyaSiddique please don't say sorry...I can understand it...you're a Project Admin as well as Maintainer...you've lots of work to do...So no worries...it's upon you...nothing to say sorry....totally understandable..I was saying @Sarthakkashyapp to be independent....you can give him the issue...  Thanks for understanding!! @AlfiyaSiddique   
> 
> 
> @Sarthakkashyapp dear,kindly,don't say vague stuffs now..don't get diverted..the comments are more clearer..

Just trying to be nice with you nothing else and also I understand you are telling me to raise issue independently and that's correct so go for it now.

**Comment by ark0078** [comment]
> I request both of you to not argue on this. Let's solve this out. @ark0078 please work on this as you have opened it, let me know your decision. Due to dealing with so many PR and Issues, I did this mistake I am apologizing one more time, Please let me know @ark0078 if you are up for this or not.

@Sarthakkashyapp will take it....pls assign it to him...I'll better open another issue.

**Comment by ark0078** [comment]
> > I request both of you to not argue on this. Let's solve this out. @ark0078 please work on this as you have opened it, let me know your decision. Due to dealing with so many PR and Issues, I did this mistake I am apologizing one more time, Please let me know @ark0078 if you are up for this or not.
> 
> @Sarthakkashyapp will take it....pls assign it to him...I'll better open another issue.

@AlfiyaSiddique assign it to him

**Comment by AlfiyaSiddique** [comment]
I agree that the mistake is mine
However, I am highly disappointed by the taunting or attacking language used in this discussion by both of you. I believe this can be handled by more subtle words, we all are humans and mistakes happen. Blaming people out of instinct is not a solution.
this is not accepted behavior and violates the code of conduct.
Please note that Next time using such language can block you from contributing to this project.
Hope you understand!

@Sarthakkashyapp let me know if you want to work, as @ark0078 not willing to work on this.

**Comment by ark0078** [comment]
> I agree that the mistake is mine However, I am highly disappointed by the taunting or attacking language used in this discussion by both of you. I believe this can be handled by more subtle words, we all are humans and mistakes happen. Blaming people out of instinct is not a solution. this is not accepted behavior and violates the code of conduct. Please note that Next time using such language can block you from contributing to this project. Hope you understand!
> 
> @Sarthakkashyapp let me know if you want to work, as @ark0078 not willing to work on this.

@AlfiyaSiddique I'm really sorry if I use any wrong words..Kindly do pardon me..sorry again..

**Comment by Sarthakkashyapp** [comment]
> I agree that the mistake is mine
> However, I am highly disappointed by the taunting or attacking language used in this discussion by both of you. I believe this can be handled by more subtle words, we all are humans and mistakes happen. Blaming people out of instinct is not a solution.
> this is not accepted behavior and violates the code of conduct.
> Please note that Next time using such language can block you from contributing to this project.
> Hope you understand!
> 
> @Sarthakkashyapp let me know if you want to work, as @ark0078 not willing to work on this.

I am sorry @AlfiyaSiddique for my words and if that is the case I am in for contribution 👍🏻

**Comment by AlfiyaSiddique** [comment]
Okay @Sarthakkashyapp, once you reply to the queries here -> https://github.com/AlfiyaSiddique/TastyTrails/issues/183#issuecomment-2408570138
and all questions related to this issue are resolved,  it will get assigned to you.

**Comment by Sarthakkashyapp** [comment]
> Okay @Sarthakkashyapp, once you reply to the queries here -> https://github.com/AlfiyaSiddique/TastyTrails/issues/183#issuecomment-2408570138
> and all questions related to this issue are resolved,  it will get assigned to you.
> 
> 

Okay @AlfiyaSiddique

**Comment by Sarthakkashyapp** [comment]
> @Sarthakkashyapp Do not add the cookie part and trusted third-party section as this is not relevant for our site. We only collect data for registration and feedback messages. There is no cookie implemented as of now other than session functionality I guess.
> 
> We also do not have the feature to delete user accounts as of now. 
> So tell me in short what points we can add then you have to draft the contents for those points if accepted.
> And then propose a policy page design after this the issue will be assigned to you and you can start implementing.
> Let me know if you are up for this.

Given the information you shared, here's the best approach for a privacy policy tailored to **TastyTrails**:

### Key Points for TastyTrails Privacy Policy:

1. **Introduction**
   - Clearly state that TastyTrails values user privacy and outlines the minimal data collected.

2. **Information We Collect**
   - **Registration Data:** Mention that the only personal data collected is for user registration (name, email).
   - **Feedback Messages:** Collecting information users submit via the feedback form.

3. **How We Use Your Information**
   - **For Registration:** To manage and create user accounts.
   - **For Feedback Improvement:** To improve the user experience based on the feedback provided.
   - **For Communication:** Send updates or necessary information related to their account or feedback.

4. **Data Security**
   - Explain that security measures are in place to protect user data, including session management for authentication.
   
5. **User Rights**
   - Mention that users can view or update their account information but clarify that the feature to delete accounts is not available yet.
   - Provide a method for users to request changes to their data if needed (e.g., email support).

6. **Contact Us**
   - Provide a simple way for users to contact the TastyTrails team with privacy-related questions or concerns.

---

This streamlined policy will cover all the necessary points based on the limited data collected and the features currently implemented on the site. There’s no need for sections about cookies or third-party sharing since they’re not relevant to your site.

If these points are approved, I can draft the full content for the Privacy Policy and suggest a simple yet modern page design for it. Let me know when you're ready! @AlfiyaSiddique please look into this. Thank you

**Comment by AlfiyaSiddique** [comment]
@Sarthakkashyapp go ahead with the full content draft.

**Comment by Sarthakkashyapp** [comment]
Thank you @AlfiyaSiddique for assigning will start working soon. Also if you have any suggestions you can tell me regarding this.

**Comment by Sarthakkashyapp** [comment]
@AlfiyaSiddique please look into this kept it very simple and responsive as privacy policy should be added privacy-policy in footer, Ready to raise PR for this. Thankyou so much once again.😊

![Screenshot 2024-10-16 214903](https://github.com/user-attachments/assets/601fc9f3-57b8-404f-9b09-47a01d0169e1)
                                                          
![Screenshot 2024-10-16 214601](https://github.com/user-attachments/assets/202f668e-ce8a-42ca-91e6-455c36220eea)

**Comment by AlfiyaSiddique** [comment]
Looks good! @Sarthakkashyapp  You can raise PR. Will give further feedback on the PR.👍🏻

**Comment by Sarthakkashyapp** [comment]
> Looks good! @Sarthakkashyapp  You can raise PR. Will give further feedback on the PR.👍🏻

Glad you liked it @AlfiyaSiddique will raise PR now.
