### ISSUE TITLE
ENHANCEMENT: adding chatbot

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [AlfiyaSiddique/TastyTrails#184]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

i can add a chatbot which will be fine tuned for this website.
@AlfiyaSiddique can you please assign me this task.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@T-Rahul-prabhu-38 This is a duplicate issue of #117
