### ISSUE TITLE
FEATURE: Add debouncing while searching

### ISSUE THREAD

**Issue by shreysachani** [AlfiyaSiddique/TastyTrails#188]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

The feature aims to optimize the search functionality. Currently, a network request is triggered for every letter typed in the search bar, leading to unnecessary load on the server and poor user experience due to frequent request-response cycles. This feature will introduce a debounce mechanism that delays the network request until the user has stopped typing for a brief period (e.g., 300 milliseconds). This will reduce the number of unnecessary API calls while improving performance.

### Component

Searchbar

### It should be implemented because

Without the debounce mechanism, each keystroke sends a request to the server, leading to:

High server load due to multiple unnecessary requests.
Increased latency and poor user experience with constant request-response cycles.

With debounce:

Only one request will be sent after the user has stopped typing, reducing server load.
Improved user experience as the search results will appear after a short delay, preventing "flickering" as the user types.
A cleaner, more efficient codebase with better performance and responsiveness.

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [ ] I'm a GSSOC'24 Ext contributor

**Comment by shreysachani** [comment]
Please assign this issue to me under hacktoberfest

**Comment by AlfiyaSiddique** [comment]
@shreysachani thanks for opening this issue.
can you paste here the part of the code that triggers a network request on each search letter hit?

**Comment by shreysachani** [comment]
Yes sure. Here is the piece of code

const Recipes = ({type}) => {
  const [loading, setLoading] = useState(true);
  const [recipes, setRecipes] = useState([]);
  const backendURL = import.meta.env.VITE_BACKEND_URL;
  const [pagination, setPagination] = useState({
    totalRecipes: 5,
    currentPage: 1,
    totalPages: 1
  });
  const [searchTerm, setSearchTerm] = useState("");
  const limit = 10;

  useEffect(() => {
    const fetchRecipes = async () => {
      try {
        const response = await axios.get(`${backendURL}/api/recipes`, {
          params: {
            page: pagination.currentPage,
            limit,
            type,
            search: searchTerm,
          },
        });

        const { recipes, pagination: paginationData } = response.data;     
          
        setRecipes(recipes);
     
        setPagination((prev) => ({
          ...prev,
          totalRecipes: paginationData.totalRecipes,
          totalPages: paginationData.totalPages
        }));
      } catch (err) {
        console.log(err);
      }finally{
        setLoading(false);
      }
    };

    fetchRecipes();
  }, [pagination.currentPage, type, searchTerm]); 

  const handleSearch = (e) => {
    const value = e.target.value;
    setSearchTerm(value);
  };
  
  
   <input
          type="search"
          id="default-search"
          className="block p-3 w-full ps-10 text-sm text-gray-900 border border-red-300 rounded-lg focus:ring-red-500 focus:border-red-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-red-500 outline-none"
          placeholder="Search Recipes with Name"
          required
          value={searchTerm}
          onChange={handleSearch}
        />
        

- So on the input field that is the search bar there is onChange property that means whenever user types a character 
  handleSearch function is triggered.
- handleSearch function captures what user inputs and changes the value of state by setSearchTerm
- Now in useEffect, searchTerm is set in dependency array which means whenever the value of state searchTerm changes 
   useEffect is called and inside useEffect fetchRecipes function makes an API request. So each time a user inputs some thing an 
   API call is sent to the server.

**Comment by AlfiyaSiddique** [comment]
@shreysachani  in UseEffect:
>useEffect(() => {
const fetchRecipes = async () => {
try {
const response = await axios.get(${backendURL}/api/recipes, {
params: {
page: pagination.currentPage,
limit,
type,
search: searchTerm,
},
});

There is no dependency array. So the last point is not valid.
But you can work on this part of code if you can refactor in any better way.
assigning to you.

**Comment by shreysachani** [comment]
Started working on this issue.

**Comment by AlfiyaSiddique** [comment]
Okay understood, Please fix that.
Thanks for opening this issue
