### ISSUE TITLE
Issue Title: "Add Chatbot Feature"

### ISSUE THREAD

**Issue by AswaniBolisetti** [AlfiyaSiddique/TastyTrails#190]
@AlfiyaSiddique 
Issue Description: I would like to add a chatbot feature to the website to enhance user support and engagement. The chatbot will provide instant assistance to users by answering common queries, offering guidance, and directing them to relevant sections of the site.

Please assign this issue to me under the labels: level3, gssoc-ext, and hacktoberfest-accepted.

**Comment by AlfiyaSiddique** [comment]
@AswaniBolisetti what kind of querries it will solve?

**Comment by AlfiyaSiddique** [comment]
Closing due to no reply
