### ISSUE TITLE
ENHANCEMENT: Fallback for Font-Family

### ISSUE THREAD

**Issue by Prasanna1055** [AlfiyaSiddique/TastyTrails#191]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

I think it would be a good idea to provide a broader range of fallback fonts in case 'Roboto' doesn’t load like Helvetica Neue.

### Component

typography

### It should be implemented because

1. When a primary font is missing glyphs needed to render content, a fallback font is used instead.
2. Fallback fonts can help improve the reading experience. 
3. Fallback fonts help ensure that everything on the web degrades gracefully. 

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@Prasanna1055 change in font family issue is already present : #23 . It's a duplicate issue
