### ISSUE TITLE
ENHANCEMENT: 

### ISSUE THREAD

**Issue by Sarthakkashyapp** [AlfiyaSiddique/TastyTrails#192]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

Adding the skeleton loading when the images does not load properly it make the page look more professional and also user does not experience a blank space when images doesn't load properly. I would like to get started working on this issue please assign me under labels **gssoc-ext** and **hacktoberfest** and **level2**. (Take reference from the image)
![Screenshot 2024-10-12 151629](https://github.com/user-attachments/assets/aac8fa35-ad00-41a4-98fa-790876018e2c)

### Component

The home page where the recipe images are visible.

### It should be implemented because

it should be implemented for a good ui as good user experience overall.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@Sarthakkashyapp I am assigning this issue to you. But some imp details below.

Earlier there was some work on the skeleton loading feature but at times it did not work properly. Also, the current skeleton for recipes just looks like a box. So please improve all of this.
The level label will be assigned on the PR

**Comment by Sarthakkashyapp** [comment]
@AlfiyaSiddique Thankyou for assigning I'll do my best.
