### ISSUE TITLE
ENHANCEMENT: Adding More Recipes And Removing Incorrect or Gibberish Entries

### ISSUE THREAD

**Issue by IkkiOcean** [AlfiyaSiddique/TastyTrails#194]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

We need to expand the recipe collection on Tasty Trails by adding more quality recipes while cleaning up the existing database by removing incorrect or gibberish entries. Some recipes currently have invalid data, such as nonsense values in the ingredients or steps sections, which impacts the overall user experience.

### Component

The database of the application with proper entries 

### It should be implemented because

- **Enhanced User Experience**: Users will have access to a larger selection of properly formatted and useful recipes.
- **Data Quality**: Cleaning up the recipe database ensures a more reliable and enjoyable browsing experience for users.
- **Increased Engagement**: By offering a wider and cleaner selection of recipes, users are more likely to return to the platform for their cooking needs.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@IkkiOcean you cannot remove the gibberish recipes as it is from the database and you do not have access to it.  Also adding a new recipe is a use-case and not an issue.
Thanks for showing interest
