### ISSUE TITLE
Feature Request: Add User Profiles & Recipe Contributions Feature

### ISSUE THREAD

**Issue by muskan171105** [AlfiyaSiddique/TastyTrails#196]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

The feature will allow users to create personalized profiles, upload recipes, and engage with others. Users can register, login, and upload recipes including a title, ingredients, instructions, and an image. Additionally, users can view their uploaded recipes on their profile and comment on others' recipes. This fosters community interaction and recipe sharing.

### Component

Add feature to /user-profile and /upload-recipe.

### It should be implemented because

This feature enhances user engagement, enabling the platform to foster a community-driven experience where users can contribute, interact, and explore recipes. It aligns with the goal of making TastyTrails a collaborative platform.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@muskan171105 all the features mentioned is already implemented please take a look at deployed link
