### ISSUE TITLE
FEATURE: Add Social Sharing and Follower System

### ISSUE THREAD

**Issue by muskan171105** [AlfiyaSiddique/TastyTrails#197]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Add the ability for users to follow other profiles and share recipes on social media platforms like Twitter, Facebook, and Instagram. Followers will receive updates in their feed when the followed user uploads new recipes or adds comments.

### Component

Add this feature to user profiles and recipe detail pages

### It should be implemented because

This will boost user engagement, encouraging social sharing of content and allowing users to stay connected with other contributors on the platform.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@muskan171105 duplicate issue of #152 & #112 
you can keep an eye on these issues and be in the queue to get assigned by commenting. If find no updates from previous contributor the next contributor in queue will be assigned
