### ISSUE TITLE
Adding Contributors page

### ISSUE THREAD

**Issue by TBorundia** [AlfiyaSiddique/TastyTrails#198]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

I can add the option to navigate contributor page.
I will show the github profile of all the contributors worked for the project.

### Component

I will ensure to make the page UI similar to the theme and also responsive for all screens.
It will directly fetch the data from the repository.

### It should be implemented because

It will show,
Transparency: It shows transparency in the project's development and highlights the collaborative effort behind it.
Engagement: It helps build a community by encouraging more people to contribute and get involved.
Networking: It provides an opportunity for users to connect with contributors, potentially leading to more collaboration and support.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@TBorundia go ahead, make the contributor page style match with the other theme
