### ISSUE TITLE
ENHANCEMENT: Re-making the Navigation bar and footer

### ISSUE THREAD

**Issue by shubhamjh15** [AlfiyaSiddique/TastyTrails#199]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

Improving the UI of the navigation bar and also re making the footer with animations and also adding the copyright section

### Component

header and footer

### It should be implemented because

It will enhance the user experience with quick access to important links

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@shubhamjh15 please provide the new design of navbar and footer

**Comment by shubhamjh15** [comment]
@AlfiyaSiddique  
![Screenshot 2024-10-12 232528](https://github.com/user-attachments/assets/0629c817-a7f9-4898-9687-24e4ef9c7adb)
heres the nav bar
the nav content has simple hover animation and ive added border bottom for more clarity

**Comment by AlfiyaSiddique** [comment]
@shubhamjh15 the given design is not much different from the current navbar, it is almost same.
Also there's already lot of work going around the navbar design so I am closing this issue as it is not needed
