### ISSUE TITLE
Notification Button

### ISSUE THREAD

**Issue by TanmayKalra09** [AlfiyaSiddique/TastyTrails#20]
Hi @AlfiyaSiddique I would like to add the notification button on the nav bar which will redirect the user to the notification page.

Please assign me this issue under GSSOC Extended and Hactoberfest :)

**Comment by AlfiyaSiddique** [comment]
@TanmayKalra09 
Go ahead with it and please clear your previous issues if have any or the questions asked on them.

**Comment by TanmayKalra09** [comment]
> @TanmayKalra09 Go ahead with it and please clear your previous issues if have any or the questions asked on them.

Thank you for assigning the issue and I have answered your query in https://github.com/AlfiyaSiddique/TastyTrails/issues/9
