### ISSUE TITLE
ENHANCEMENT: Implement Favorite (heart) Functionality for Recipes

### ISSUE THREAD

**Issue by Laxmi01345** [AlfiyaSiddique/TastyTrails#200]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

Implement Favorite Functionality for Recipes
This feature will allow users to mark a recipe as their favourite by clicking a heart icon, increasing the favourite count.

### Component

/recipes 

### It should be implemented because

It should be implemented because:

1. Improved User Engagement: Allowing users to favourite recipes will increase engagement by allowing them to interact with the content more meaningfully.
2. Personalization: Users can easily access their favourite recipes later, offering a more personalized and user-friendly experience.
4. Enhanced User Retention: The feature encourages users to return to the app more frequently to view or try their favourites by enabling them to save recipes they like.
5. Content Value: Adding a favourite option gives users the ability to express what content they value, which can help in future content recommendations or personalization.
6. Competitive Feature: Many recipe and content-based applications provide similar functionality. Implementing this ensures our platform remains competitive and aligned with user expectations.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@Laxmi01345 The features of like and dislike are already under development in #6 . And I think like and favorite recipes would be same feature.
