### ISSUE TITLE
BUG: Extra Semicolon

### ISSUE THREAD

**Issue by Sameeratweb** [AlfiyaSiddique/TastyTrails#203]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe your issue

![Screenshot 2024-10-12 231657](https://github.com/user-attachments/assets/f97f2af0-a189-478b-ab10-ac7a639de583)
Maybe due to a typo, some extra semicolons are present. I can work on fixing this.

### Steps to reproduce

In Footer Section 
below the logo of TastyTrials an extra semicolon maybe seen.

### What was the expected result?

Footer section will be efficient for navigation purposes

### Proposed solution

Reviewing the code and checking for any corrections

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@Sameeratweb  please go ahead fix it soon

**Comment by Sameeratweb** [comment]
Could you please provide more details about the section where it happened and how it occurred?

**Comment by AlfiyaSiddique** [comment]
@Sameeratweb mostly in the footer part you can figure it out.
Mostly it is your part of work.
Let me know if you need any specific help

**Comment by AlfiyaSiddique** [comment]
@Sameeratweb any updates?

**Comment by biswajit-sarkar-007** [comment]
@AlfiyaSiddique hey i want to work on this issue should you assign to me ?

**Comment by AlfiyaSiddique** [comment]
Assigning to @biswajit-sarkar-007 due to no response from the assigned contributor

**Comment by AlfiyaSiddique** [comment]
Please fix it soon
