### ISSUE TITLE
FEATURE: Github Workflow : Notify Contributors When Pull Requests Are Merged

### ISSUE THREAD

**Issue by samyak-aditya** [AlfiyaSiddique/TastyTrails#205]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Notify Contributors When Pull Requests Are Merged

### Issue Description
**Background:**
Currently, when a pull request (PR) is merged, contributors are not notified about the status of their contributions. It’s important to acknowledge their efforts and keep them informed to foster a positive and collaborative environment.

Hey @AlfiyaSiddique   Please assign me this issue with "level3"

### Component

N/A

### It should be implemented because

**Benefits:**
- Enhances contributor engagement.
- Acknowledges their work, which can encourage future contributions.
- Improves communication within the project.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@samyak-aditya are you talking about adding an automatic comment of acknowledgement after the PR is merged?

**Comment by samyak-aditya** [comment]
@AlfiyaSiddique yes

**Comment by AlfiyaSiddique** [comment]
Okay @samyak-adityan you can work on this but the label level will not be 3.  It could be 2 or 1.
Let me know what you say.

**Comment by samyak-aditya** [comment]
Set it level2 , thanks

**Comment by AlfiyaSiddique** [comment]
The level will be assigned to PR. If you want you can start working on this. Assigning to you

**Comment by samyak-aditya** [comment]
@AlfiyaSiddique I have raised the PR
