### ISSUE TITLE
FEATURE: Adding Animated Cursor

### ISSUE THREAD

**Issue by Mandy1200** [AlfiyaSiddique/TastyTrails#207]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

I would like to add  animated cursor for better user friendly interface and effects

### Component

To the whole website

### It should be implemented because

For better user interface
sample
![Screenshot (119)](https://github.com/user-attachments/assets/c6ae50c3-17f7-4a45-a11a-f9e29b8841ef)

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@Mandy1200 not needed
Thanks for showing interest
