### ISSUE TITLE
FEATURE: Add Floating Social Media Iconbar on homepage

### ISSUE THREAD

**Issue by AsmitaMishra24** [AlfiyaSiddique/TastyTrails#209]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

I want to add a floating social media icon bar to the homepage of our website to improve user engagement by providing easy access to our social media profiles.

### Component

The floating social media icon bar will be added to the Homepage.

![345800664-b46c5210-a8ef-4920-a3f8-565b04c01f3b](https://github.com/user-attachments/assets/14e3e8a2-3327-488a-95dc-432b359bf672)

![videoframe_0](https://github.com/user-attachments/assets/bf0b65e3-4b5c-4fe1-bdfe-e80462665aee)

https://github.com/user-attachments/assets/d08e0aab-3580-4fc4-911c-4b7688cd6266

### It should be implemented because

Adding a floating social media icon bar will help increase social media engagement and visibility. It encourages visitors to follow the brand or share content directly from the homepage, boosting both brand presence and organic reach.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@AsmitaMishra24 is not needed.
Thanks for showing interest
