### ISSUE TITLE
ENHANCEMENT: Improving UI 

### ISSUE THREAD

**Issue by shreya20v** [AlfiyaSiddique/TastyTrails#210]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

Improving UI of the home page which includes: introduction, features, world's best dishes, and about us. 
@AlfiyaSiddique I would like to work on this issue. Please assign it to me under gssoc-exd, hacktoberfest, and the appropriate level label.

### Component

![image](https://github.com/user-attachments/assets/e1f6a5b4-7e3c-45c4-b469-21afc633229b)
![image](https://github.com/user-attachments/assets/fa6ede81-a6d5-4710-84b4-1e2210899a73)
![image](https://github.com/user-attachments/assets/180ffee2-33b7-4b56-9c65-e372bb71ff12)

### It should be implemented because

It will beautify the website and make it more attractive to the user.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
A lot of work is already going around UI so not needed.

**Comment by AlfiyaSiddique** [comment]
Thanks for showing interest @shreya20v
