### ISSUE TITLE
BUG: Fix Footer Layout Overflow for Large Screens

### ISSUE THREAD

**Issue by Arpin007** [AlfiyaSiddique/TastyTrails#216]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe your issue

The footer component overflows its container on a larger screen, leading to layout issues.
![image](https://github.com/user-attachments/assets/03ad3924-e297-4553-abc4-9b5d8f02d724)

@AlfiyaSiddique Please assign it to me & mark the relevant tags...

### Steps to reproduce

..

### What was the expected result?

..

### Proposed solution

..

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by Arpin007** [comment]
@AlfiyaSiddique I have made some more changes in the text size & icon size.
This is the exciting text & logo
![image](https://github.com/user-attachments/assets/b229aa5e-84a2-46c5-ad9e-6263c6af9b6d)

after changing
![image](https://github.com/user-attachments/assets/5eced90c-bfa1-4ed9-aaaf-ca1cb33c816f)

**Comment by AlfiyaSiddique** [comment]
@Arpin007 can you share at which media size you are getting this issue?

**Comment by Arpin007** [comment]
The overflow issue starting at the 1536px media size, which corresponds to the 2xl breakpoint in Tailwind CSS. The issue occurs on screens wider than this size."

**Comment by AlfiyaSiddique** [comment]
@Arpin007 go ahead assigning to you. Please Fix this issue

**Comment by Arpin007** [comment]
@AlfiyaSiddique Please add level...
