### ISSUE TITLE
FEATURE: Change Required Field Validation from Alert Windows to User-Friendly Messages

### ISSUE THREAD

**Issue by ananyag309** [AlfiyaSiddique/TastyTrails#217]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Currently, the application displays required field validation messages through alert windows. This approach interrupts the user experience and can lead to frustration. 

![image](https://github.com/user-attachments/assets/4c403cbc-f87f-4764-ace4-5b073bccc643)

 I recommend implementing inline error messages or using tooltips to display validation messages next to the relevant input fields. This change will provide a more user-friendly experience by allowing users to see errors without disrupting their workflow.

### Component

at feedback form

### It should be implemented because

Benefits of the Change:

Improves user experience by reducing interruptions.
Allows users to correct errors immediately without navigating through alert windows.
Makes the form more intuitive and easier to use.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@ananyag309 go ahaed

**Comment by govindumeesala** [comment]
can I work on it @AlfiyaSiddique

**Comment by AlfiyaSiddique** [comment]
@ananyag309 any updates?

**Comment by ananyag309** [comment]
will be done today
