### ISSUE TITLE
BUG: Implement Character Length Validation on Feedback Message

### ISSUE THREAD

**Issue by ananyag309** [AlfiyaSiddique/TastyTrails#218]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe your issue

The current implementation allows users to submit feedback messages with a minimum character length of just one letter. This can lead to unhelpful or meaningless feedback submissions.

### Steps to reproduce

 I suggest imposing a character length validation that requires feedback messages to have a minimum of at least [insert minimum character length, e.g., 5 or 10] characters. This will ensure that submitted feedback is meaningful and constructive.

### What was the expected result?

Benefits of the Change:

Encourages users to provide more thoughtful and detailed feedback.
Reduces the number of submissions that contain insufficient information.
Enhances the quality of data collected for analysis and improvements.

### Proposed solution

just change the validation of feedback form

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@ananyag309 go ahaed
