### ISSUE TITLE
FEATURE: Add "Remember Me" Feature to Login Page

### ISSUE THREAD

**Issue by ananyag309** [AlfiyaSiddique/TastyTrails#219]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Currently, the login page does not have a "Remember Me" option for users. This feature is commonly used to enhance user experience by allowing users to stay logged in for future sessions.

### Component

Implement a "Remember Me" checkbox on the login page. When selected, this option should:

Store user credentials securely (e.g., using cookies or local storage) to keep the user logged in on subsequent visits.
Allow users to easily return to the application without needing to re-enter their credentials.

### It should be implemented because

Improves user convenience by reducing the frequency of logins.
Enhances user experience, especially for those who frequently access the application.
Potentially increases user engagement and retention.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@ananyag309 by default session is implemented for an interval for all logins, so not needed.
Thanks for showing interest.
