### ISSUE TITLE
ENHANCEMENT: Add HOME option in navbar.

### ISSUE THREAD

**Issue by shambhavipathak24** [AlfiyaSiddique/TastyTrails#220]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

I would like to add home option in navbar so that user not get confuse how to come back on main page.

### Component

Navbar

### It should be implemented because

On addition of home option user don't case confuse and they easily back to main page..

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by MohammedMusharraf11** [comment]
Can you @AlfiyaSiddique Assign it to me
I would love to work on that

**Comment by AlfiyaSiddique** [comment]
@shambhavipathak24  it is already there in the navbar when you click on the TastyTrails text.
Thanks for showing interest
