### ISSUE TITLE
FEATURE: add language translator

### ISSUE THREAD

**Issue by ananyag309** [AlfiyaSiddique/TastyTrails#222]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

To add a language translator to your website, you can use the Google Translate widget or similar APIs. This allows dynamic translation of content, enhancing accessibility for users speaking different languages with minimal efforts.

### Component

main file

### It should be implemented because

this allows dynamic translation of content, enhancing accessibility for users speaking different languages.

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by xuqssq** [comment]
我可以做这个需求

**Comment by AlfiyaSiddique** [comment]
@ananyag309 & @xuqssq this feature is already under development in #193 
Thanks for showing interest
