### ISSUE TITLE
ENHANCEMENT: Enhance Navbar Design: Improve Visibility and Accessibility of "Navbar" to the user.

### ISSUE THREAD

**Issue by kekubhai** [AlfiyaSiddique/TastyTrails#223]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

Separate "Navbar": The "Navbar" option will be visually separated within the navbar, creating a clearer distinction from other navigation elements. This will make it easier to identify and understand for users.
Enhance design effects: The "Navbar" element will receive design enhancements, such as improved typography, color schemes, and visual elements, to make it more visually appealing and engaging within the navbar's context.

### Component

![image](https://github.com/user-attachments/assets/772fdf1e-0309-4e8f-9922-5de049473680)

### It should be implemented because

A navbar with a more visually appealing and user-friendly design, where the "Navbar" offer is clearly distinguishable and easily accessible to users. The enhanced design effects will contribute to a more engaging and enjoyable user experience within the navbar.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@kekubhai not needed

**Comment by AlfiyaSiddique** [comment]
Thanks for showing interest :)
