### ISSUE TITLE
Signup card overflow on navbar

### ISSUE THREAD

**Issue by aditya07389** [AlfiyaSiddique/TastyTrails#225]
hey @AlfiyaSiddique 
i want to work on the following 

1) add a dark mode feauture , many people prefer dark mode , so i can add up a toggle button which switches between the modes !

2) Signup container is touching the navbar , i would want to fix that !
![image](https://github.com/user-attachments/assets/38213b7a-6e50-40e9-b0e9-e13ed48ecf9b)

Kindly assign this work to me under gssoc extd and hacktoberfest accepted labels 
Thankyou !

**Comment by AlfiyaSiddique** [comment]
@aditya07389  please go ahead and fix it soon:)
Thanks for opening this issue

**Comment by aditya07389** [comment]
Sure @AlfiyaSiddique 
I'll raise pr by evening, thankyou

**Comment by AlfiyaSiddique** [comment]
@aditya07389 any updates?

**Comment by aditya07389** [comment]
I am really sorry but I'm not able to resolve the issue, sorry for the delay :(

**Comment by AlfiyaSiddique** [comment]
Okay @aditya07389 no worries, opening for another assigner then
