### ISSUE TITLE
FEATURE: Improving social icons 

### ISSUE THREAD

**Issue by PATILYASHH** [AlfiyaSiddique/TastyTrails#226]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

The Social icons are not good looking its need to improve by adding hover effects and animations in it  

![image](https://github.com/user-attachments/assets/7be487ae-b1e1-498d-9e4d-9c2b226e7aa7)

### Component

footer

### It should be implemented because

the current icons are not good to see with websites overall design 

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@PATILYASHH not needed
Thanks for showing interest
