### ISSUE TITLE
ENHANCEMENT: Improve the recipe section

### ISSUE THREAD

**Issue by PATILYASHH** [AlfiyaSiddique/TastyTrails#227]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

![image](https://github.com/user-attachments/assets/3dfe084f-7dfe-4e4b-bc87-96ed84275a9f)

The List of Ingredients and Steps area need to improve with simple and easy to read structure 

### Component

/List of Ingredients and /Steps

### It should be implemented because

its not user friendly with that current structure of steps and list of ingredients 

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@PATILYASHH I think this is an already open issue under fixing the layout of recipe page so you can find that and comment below that to get assigned if no one is working.
Thanks for showing interest
