### ISSUE TITLE
FEATURE : Implement a Frequently Asked Questions (FAQ) popup modal to the main page for quick user assistance.

### ISSUE THREAD

**Issue by rajgharat07** [AlfiyaSiddique/TastyTrails#232]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Description : 
- Users often struggle to find answers to common questions, leading to frustration and delays in using the site effectively. I'm always frustrated when I have to search through multiple pages or support channels to find basic information about features or services.

### Solution I would like to Propose : 
- I would like to implement a Frequently Asked Questions (FAQ) popup modal on the main page. This would provide users with instant access to commonly asked questions in an organized and searchable format without navigating away from the main content. The modal should be easily accessible through a button or link, and display in a user-friendly, visually appealing layout.

### Alternatives I've considered : 

- I will manage the FAQ questions in a separate file to keep them dynamic and easily maintainable, rather than hardcoding them directly into the codebase.

### Additional context : 
- This feature could enhance user experience by making the site more user-friendly and reducing the need for customer support.

### Component

https://delightful-daifuku-a9f6ea.netlify.app/

### It should be implemented because

- Enhanced User Experience : By providing quick access to frequently asked questions, users can easily find answers to common queries without leaving the main page, improving the overall user experience.

- Reduced Support Queries : Having an FAQ modal readily available reduces the number of repetitive inquiries to customer support, saving time and resources for both the support team and users.

- Convenience and Accessibility : Users can access helpful information instantly, which adds to the ease of navigation and makes the site more user-friendly.

- Improved Engagement : By keeping users engaged on the main page with quick, helpful information, the FAQ modal can help lower bounce rates and encourage longer sessions on the site.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@rajgharat07 not needed

**Comment by AlfiyaSiddique** [comment]
Thanks for showing interest
