### ISSUE TITLE
FEATURE:  Add Dark mode to the website 

### ISSUE THREAD

**Issue by Anjalis14** [AlfiyaSiddique/TastyTrails#234]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

adding dark mode to the website will make it more attractive

### Component

adding dark mode toggle button 

### It should be implemented because

it will enhance the website look

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by Anjalis14** [comment]
@AlfiyaSiddique plz assign me this

**Comment by AlfiyaSiddique** [comment]
@Anjalis14 duplicate issue
