### ISSUE TITLE
FEATURE: Profile Picture Functionality

### ISSUE THREAD

**Issue by k3uual** [AlfiyaSiddique/TastyTrails#237]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

- **Allow users to upload a profile picture during the signup process.**
- **Provide users with the ability to add or update their profile picture from the user dashboard.**

### Component

**This feature/component will be added on:**
- https://delightful-daifuku-a9f6ea.netlify.app/user/userHash
- https://delightful-daifuku-a9f6ea.netlify.app/signup

### It should be implemented because

- **It will enhance user experience**
- **It will create more personalized and engaging experience for users**
- **Moreover it will meet users expectations and will align with modern application standards** 

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@k3uual Great initiatiive
Please go ahead.
Use MongoDB to store image files

**Comment by k3uual** [comment]
> @k3uual Great initiatiive Please go ahead. Use MongoDB to store image files

Ok will do, Thank you

**Comment by sadath2001** [comment]
hi @AlfiyaSiddique , i can work in this if this is still open and if there is no opdate.

**Comment by AlfiyaSiddique** [comment]
@k3uual any updates?
