### ISSUE TITLE
FEATURE: Features Page

### ISSUE THREAD

**Issue by govindumeesala** [AlfiyaSiddique/TastyTrails#238]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Adding a pages that shows features that we offer gives more readability and enhances user experience.

And linking it to the footer.

### Component

/features

### It should be implemented because

It will help users to know about the features we offer through the platform

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@govindumeesala thanks for showing interest but this page is not a requirement
