### ISSUE TITLE
ENHANCEMENT: unusual scroll behavior because of footer and misalignment.

### ISSUE THREAD

**Issue by Sarthakkashyapp** [AlfiyaSiddique/TastyTrails#241]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

The footer items needs to be aligned and the footer is creating an unusual scroll behavior as we reaches to the end it is hiding some content of the page. I will make it relative so that it doesn't hide any contents and fix alignments making it responsive.
                
![Screenshot 2024-10-16 213430](https://github.com/user-attachments/assets/7057bb0c-0b22-4b1e-adbb-fd3de65eee42)

![Screenshot 2024-10-16 223003](https://github.com/user-attachments/assets/1a57cbd2-8f36-4c9c-a991-59c8b0132efe)

here as you can see because of footer the content is hiding.

@AlfiyaSiddique I would like to work on this and solve this issue.

### Component

i would like to improve footer behavior for the scrolling as well as alignment of items of footer.

### It should be implemented because

it is important so that user can see the full page without experiencing any odd behavior such as hidden contents or partially visible contents.

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@Sarthakkashyapp please go ahead and fix it as soon as possible.
Thanks for noticing this!

**Comment by Sarthakkashyapp** [comment]
> @Sarthakkashyapp please go ahead and fix it as soon as possible.
> Thanks for noticing this!

Thankyou @AlfiyaSiddique for assigning. I'll fix this asap.
