### ISSUE TITLE
FEATURE: Adding dark mode feature

### ISSUE THREAD

**Issue by sushil-sagar05** [AlfiyaSiddique/TastyTrails#242]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

What about adding a dark mode feature on the navbar . sometimes light mode affects user experience, especially for those who prefer dark mode for better visibility and reduced eye strain. 
Please assign me to add this feature on this project under hacktoberfest and gssoc labels.

### Component

/navbar

### It should be implemented because

for those who prefer dark mode for better visibility and reduced eye strain. 

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@sushil-sagar05 Already in development #57
