### ISSUE TITLE
ENHANCEMENT: Like and Share is not working at recepies page

### ISSUE THREAD

**Issue by raj-adi00** [AlfiyaSiddique/TastyTrails#243]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

I will add a section of liked post for each user in database which will help me fetch data if it is liked by user and i can update ui accordingly. Currently there is no option for like. I can write backend controller to like unlike any receipie and update accordingly.

### Component

![image](https://github.com/user-attachments/assets/fb17716c-895d-4087-86e5-84191237bec6)
i want to enable like and share feature in the post

### It should be implemented because

This feature will help user keep his/her choice stored and it can be displayed in therir profile

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@raj-adi00 this feature is under development in #6
