### ISSUE TITLE
FEATURE: Add Metrics Table to README

### ISSUE THREAD

**Issue by neeru24** [AlfiyaSiddique/TastyTrails#247]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

To provide a quick overview of the project’s popularity and community engagement, we should add a metrics table to the README file. 

### Component

Action Items:

- Gather current metrics from GitHub.
- Implement the metrics table in the README file.
- Automatically update the table to reflect accurate counts.

### It should be implemented because

This table will display key statistics, including the number of pull requests, stars, and forks, helping new users and contributors understand the project’s activity level.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@neeru24 go ahaed
