### ISSUE TITLE
FEATURE: Error Handling MiddleWare

### ISSUE THREAD

**Issue by DevKanmi** [AlfiyaSiddique/TastyTrails#253]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

I would like to work on an error handling middleware which is called on when the next function is used in order to display meaningful messages to the users of the API

### Component

/backend/middlewares/errorHandler.js

To be used in the the server.js file, a function called from the errorHandeler
app.use(errorHandler)

### It should be implemented because

A case where the controller is not able to catch possible errors that might have occured, a scenario of an invalid jwt token or missing token, the next function is called and the errorhandler responds with a proper meaningful message describing what the error is and where it might have occured.

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [ ] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@DevKanmi can you share a part of the code where the middleware will be helpful and explain the flow with an example of how it will be helpful?

**Comment by DevKanmi** [comment]
`An example here`: @AlfiyaSiddique 
- A user attempts to create a new recipe by sending a POST request to your API. They provide the recipe details in the request body. However, they forget to include a neccessary field (e.g., the recipe name) or send they invalid data types. The errorhandler middleware will handle any errors that arise during this process.

Something like : if (!name) {
            return next(new ApiError("Recipe name is required", StatusCodes.BAD_REQUEST));
        }
 
If this is not neccessary I would like to Work on data validations using zod, so as to ensure the right data is being passed to the db to ensure data integrity.


> @DevKanmi can you share a part of the code where the middleware will be helpful and explain the flow with an example of how it will be helpful?

**Comment by AlfiyaSiddique** [comment]
@DevKanmi I think the middleware validation is already handled in the frontend.
For example the case of adding a Recipe, if you do not add proper data it will raise an error pop-up with a message and does not publish the recipe. So I think it's not needed, But if you have any specific area where the validation is not done please let me know here.

**Comment by AlfiyaSiddique** [comment]
Closing for now, you can reopen if find valid issue
