### ISSUE TITLE
FEATURE: Add 'Forgot Password' Option on Login Page

### ISSUE THREAD

**Issue by MohitSrivastava22** [AlfiyaSiddique/TastyTrails#257]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

I will add the Forget password option in the login page so that if any user forget his/her password he/she can easily reset their password through email
![Screenshot (204)](https://github.com/user-attachments/assets/babf7704-3f81-4701-880d-45f0b135949a)

### Component

/api/login

### It should be implemented because

It should be implemented because if any user forget their password there is no way to do login so there must be forget password so that user can reset their password
![Screenshot (204)](https://github.com/user-attachments/assets/d0a282e9-f413-4dbb-a320-1265838ef566)

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@MohitSrivastava22 This feature is already in development under the issue #10 
thanks for showing interest
