### ISSUE TITLE
FEATURE: Deletion functionality on comments

### ISSUE THREAD

**Issue by Saurabhchaudhary9799** [AlfiyaSiddique/TastyTrails#261]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

This feature is regarding the deleting functionality on comments. If any user wants to delete its comment , then user can delete its comment.

### Component

I would like add this feature in  /api/recipe/delete-comment

### It should be implemented because

- Users may post incorrect or irrelevant comments (e.g., mistakes in ingredient suggestions or cooking tips). Having the ability to delete these ensures that the conversation around the recipe remains accurate and helpful.
- Deleting comments provides users control over their content. If they change their mind about a suggestion, or realize that their comment is redundant, they can remove it. This encourages engagement without the fear of permanent mistakes.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by Saurabhchaudhary9799** [comment]
@AlfiyaSiddique , I want  to work on this issue , could you please assign this to me?

**Comment by AlfiyaSiddique** [comment]
@Saurabhchaudhary9799 please go ahead

**Comment by Saurabhchaudhary9799** [comment]
@AlfiyaSiddique , I closed this PR because of some git commits problems. I am raising  a PR again
