### ISSUE TITLE
mouse cursor

### ISSUE THREAD

**Issue by abhi200446** [AlfiyaSiddique/TastyTrails#263]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

 i will change mouse cursor  for user experience

### Component

mouse cursor

### It should be implemented because

to enhance userexperience

https://github.com/user-attachments/assets/5d961b2b-9711-4323-90ca-770265c2fd19

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@abhi200446 it is not a requirement.
thanks for showing interest

**Comment by abhi200446** [comment]
can i add logo for the navbar same as browser page fevicon please assign me  @AlfiyaSiddique

**Comment by AlfiyaSiddique** [comment]
@abhi200446 logo is also not needed.

**Comment by abhi200446** [comment]
@AlfiyaSiddique 
![image](https://github.com/user-attachments/assets/9632af3d-17d7-4696-a21f-78f93a92ce99)
can i hover this icons

**Comment by AlfiyaSiddique** [comment]
Which more icons and hover issues are already under development

**Comment by abhi200446** [comment]
@AlfiyaSiddique can u assign me any issue please to work with
