### ISSUE TITLE
ENHANCEMENT: Improve footer usability and design

### ISSUE THREAD

**Issue by Harshita9412** [AlfiyaSiddique/TastyTrails#264]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

I propose enhancing the footer of the existing module to improve usability and provide users with easier access to important information. The changes will include:

->Addition of Key Links: Integrating links to essential pages like Privacy Policy, Terms of Service, and a Contact Us page.
->Social Media Icons: Adding recognizable icons linking to the project's social media accounts for better engagement.
->Visual Design Update: Updating the layout and color scheme to ensure it aligns with the overall branding and enhances readability.

![image](https://github.com/user-attachments/assets/146b202c-cba3-4c2c-b579-cf9e92d0fe20)
creating footer something like this.

### Component

The area I would like to improve is the footer section of the application, specifically located on the home page.
https://delightful-daifuku-a9f6ea.netlify.app/

### It should be implemented because

This enhancement should be implemented for several reasons:

-> Currently, users may struggle to find critical information, such as legal terms or ways to connect with the organization. By clearly displaying these links, we can enhance navigation and user satisfaction.

-> Adding social media links can increase user engagement and foster a community around the project, encouraging users to connect and share.

-> Updating the design will ensure that the footer is visually appealing and accessible to all users, including those with disabilities. Proper contrast and layout will enhance readability.

 For instance, a user visiting the home page may want to learn more about the project’s legal framework or reach out for support. By having these links readily available in the footer, the user can easily navigate to the relevant pages, improving their experience and trust in the application.

@AlfiyaSiddique Please assign this to me.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@Harshita9412 This is already an open issue, please check here, #15
