### ISSUE TITLE
ENHANCEMENT: SignUp page

### ISSUE THREAD

**Issue by Harshita9412** [AlfiyaSiddique/TastyTrails#265]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

I propose to enhance the existing sign-up page by improving its layout, usability, and visual design. The enhancements will include:

->Redesigned Layout: A more organized structure that groups related fields and guides users through the sign-up process.
->Form Field Enhancements: Clear labels and placeholder text for each input field.
->Real-time validation and error messages to inform users about mistakes as they fill out the form.

### Component

![image](https://github.com/user-attachments/assets/dd76ed03-cb3a-4a63-b497-834ce60e302e)

### It should be implemented because

A modern and visually appealing sign-up page enhances the overall brand image, making it more attractive to new users.

For instance, a new user visiting the sign-up page may feel overwhelmed by a cluttered or unclear form. By introducing these enhancements, we provide a smoother experience that encourages them to complete the sign-up, ultimately increasing user acquisition and engagement with the application.

@AlfiyaSiddique Please assign this to me.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@Harshita9412 already an open issue #225

**Comment by AlfiyaSiddique** [comment]
@Harshita9412  ISSUE 225 is closed as the previous assignor is not able to fix it.
Are you still interested in working on this issue, if yes I'll assign you.
