### ISSUE TITLE
BUG: the navbar (header) is not sticky i would like to make it it non-scrollable. same with the footer.

### ISSUE THREAD

**Issue by vidhi-github** [AlfiyaSiddique/TastyTrails#269]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe your issue

the navbar (header) is not sticky i would like to make it it non-scrollable. same with the footer.
the footer needs to be redesigned also. kindly assign me this issue under gssoc-ext an hacktoberfest-accepted under good level issue.

### Steps to reproduce

.

### What was the expected result?

the navbar and footer should hve some good styling and should be sticky.

### Proposed solution

.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@vidhi-github you can make the navbar sticky make sure it becomes sticky only after the first 100vh
And no need to make the footer sticky, keep that as it is
