### ISSUE TITLE
BUG: Login Screen is Blank

### ISSUE THREAD

**Issue by TanmayKalra09** [AlfiyaSiddique/TastyTrails#272]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe your issue

The login screen is blank, I am not able to see any fields.
![image](https://github.com/user-attachments/assets/d77e0fbd-aeb1-4d2e-810b-d8a6e9e91fbc)

### Steps to reproduce

.

### What was the expected result?

.

### Proposed solution

.

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

pls assign me this issue

**Comment by yr1404** [comment]
If this issue is open, can I work on this one?

**Comment by AlfiyaSiddique** [comment]
@TanmayKalra09  It is not blank on the deployed link:
![image](https://github.com/user-attachments/assets/58cb2ca9-db2e-4138-b02a-7c4f71ffe42a)

It must be some setup issue on your local
