### ISSUE TITLE
BUG: A new error in GoogleTranslate page

### ISSUE THREAD

**Issue by sadath2001** [AlfiyaSiddique/TastyTrails#276]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe your issue

There is an error in code of GoogleTranslate which can be seen from console of frontend
![image](https://github.com/user-attachments/assets/78d22983-6311-4d90-bb14-e944b2504861)

### Steps to reproduce

1. goto landing page
2. inspect -> console

### What was the expected result?

It shouldnt throw any error

### Proposed solution

A slight modification in the GoogleTranslate file

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@sadath2001 I can't sse any such error:
![image](https://github.com/user-attachments/assets/65d160e1-ceaa-45f4-8625-d8e012174367)

**Comment by sadath2001** [comment]
@AlfiyaSiddique , strange, but I could see It in local.

**Comment by AlfiyaSiddique** [comment]
Okay check once if it is in the deployed app or not from your side, if not please close this issue

**Comment by sadath2001** [comment]
hi, all good in deployed app, issue only in local.
