### ISSUE TITLE
FEATURE: Bookmark Feature

### ISSUE THREAD

**Issue by TanmayKalra09** [AlfiyaSiddique/TastyTrails#277]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

In this project, users can bookmark their favorite recipes, which are conveniently displayed in a dedicated "Bookmarks" section, located next to the login/signup button.

pls assign me this issue

### Component

.

### It should be implemented because

.

### Would you like to work on this issue?

yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@TanmayKalra09  are you going to implement the frontend and backend both?

**Comment by TanmayKalra09** [comment]
No, only the frontend part.

**Comment by gurramkarthiknetha** [comment]
@AlfiyaSiddique assign some issues related to frontend under hacktober fest plz.

**Comment by gurramkarthiknetha** [comment]
i want to become contributor for your project

**Comment by AlfiyaSiddique** [comment]
@TanmayKalra09 This feature is not required and only the frontend part will not work, so closing this issue

**Comment by AlfiyaSiddique** [comment]
@gurramkarthiknetha you have to open your own issues and specify if you want to contribute as gssoc.
Also, you can find old issues which have no updates and comment below them. If there is no response from previous contributor it will get assigned to you.

**Comment by TanmayKalra09** [comment]
Can this feature be picked up further if I work on both frontend and backend?

**Comment by gurramkarthiknetha** [comment]
> @gurramkarthiknetha you have to open your own issues and specify if you want to contribute as gssoc. Also, you can find old issues which have no updates and comment below them. If there is no response from previous contributor it will get assigned to you.

ok thank you
