### ISSUE TITLE
FEATURE: Recipe of the day

### ISSUE THREAD

**Issue by TanmayKalra09** [AlfiyaSiddique/TastyTrails#278]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Before the features section on the home page, a prominently displayed "Recipe of the Day" section will catch the user's attention. When users click on the "Recipe of the Day," they will be redirected to a separate page that provides full details of the recipe, including ingredients, preparation steps, and any related tips.

### Component

..

### It should be implemented because

.

### Would you like to work on this issue?

yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@TanmayKalra09 not needen now
