### ISSUE TITLE
ENHANCEMENT: Adding auto labelling to PR's

### ISSUE THREAD

**Issue by sadath2001** [AlfiyaSiddique/TastyTrails#279]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

Adding gssoc-ext and hacktober fest ext lables automatically when raised a PR

### Component

auto-label.yml

### It should be implemented because

to auto add labels in PR, reduces manual task

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@sadath2001 ASSIGNED
