### ISSUE TITLE
Improving UI/UX of SignUp Page with user freindly experience..

### ISSUE THREAD

**Issue by tech-dhawal-03** [AlfiyaSiddique/TastyTrails#28]
The signup now looks so simple with form element being so simple. What if, the complete signup page can be enhanced with good layout, components, images, hover effects, icons...having text field with good designs....

Please assign this project under GSSoC'24 Extd..
I am GSSoC'24 Extd. Contributor...
<img width="1440" alt="Screenshot 2024-10-02 at 4 16 51 PM" src="https://github.com/user-attachments/assets/718eacad-4e12-47bd-ba30-4ffd07d87b58">

**Comment by AlfiyaSiddique** [comment]
Hey @tech-dhawal-03 
Welcome to TastyTrails. 🎉

I have some questions regarding this issue:
Isn't having a simple and clear design good?
Why the current design is not user-friendly?

These are my doubts, if you have a better design plan for the signup then please share the designs.

**Comment by AlfiyaSiddique** [comment]
@tech-dhawal-03 please reply or the issue will be closed by tomorrow due to inactivity.

**Comment by tech-dhawal-03** [comment]
Sorry, I could reply on time.. Here is the design which I am attaching which I think would be better than the current one..
<img width="1269" alt="Screenshot 2024-10-10 at 8 16 21 AM" src="https://github.com/user-attachments/assets/991b557e-c9fb-43a2-98ca-1775562280e2">

The user can switch between login and signup with ease and better UI/UX...as both the functionalities have their separate divisions on top to choose..

**Comment by tech-dhawal-03** [comment]
Switching options as below - 
![Uploading Screenshot 2024-10-10 at 8.21.14 AM.png…]()

**Comment by tech-dhawal-03** [comment]
Switching options between Login and Signup as below - 
<img width="1063" alt="Screenshot 2024-10-10 at 8 21 14 AM" src="https://github.com/user-attachments/assets/f88c1167-720f-48e7-ab84-b719aa8f9fb6">

**Comment by AlfiyaSiddique** [comment]
Okay, @tech-dhawal-03 you can work on it but please note that this is a big design change so it might take time to get approval for your changes.
Also, you need to find relevant images that match with current theme and I suggest illustration-type images to use.
Make it responsive,
As it sounds much of a work you can open separate PR for Signup and Login Page and it will get you a level 3 label each.
Let me know if you are up for this.

**Comment by sushil-sagar05** [comment]
hey @AlfiyaSiddique can you please assign this issue to me due to inactivity of first member .I will completely enhance these pages  as stated above guidelines. please assign me

**Comment by AlfiyaSiddique** [comment]
@tech-dhawal-03 any response?
@sushil-sagar05 please tag me again if there's no response from the current contributor by tomorrow evening.

**Comment by sushil-sagar05** [comment]
@AlfiyaSiddique Assign me as previous member not responding i will completely enhance the ui/ux design of sign up and login page as stated above guidelines.

**Comment by AlfiyaSiddique** [comment]
@sushil-sagar05 assigning to you but you have to share the complete design first

**Comment by sushil-sagar05** [comment]
> @sushil-sagar05 you can work on this. Please submit the designs first, if the designs are approved this will get assigned to you.

design is same as above mention above some changes with illustrations only .. illustrations is similar to this website

**Comment by sushil-sagar05** [comment]
![gssoc-5](https://github.com/user-attachments/assets/71cb1db5-7a78-4f05-8a51-0615d58f7256)
same register page is also similar to this

**Comment by AlfiyaSiddique** [comment]
@sushil-sagar05 still needs an at least the layout of the actual design with actual image or how will be the layout and responsiveness of the page will be

**Comment by sushil-sagar05** [comment]
@AlfiyaSiddique you want  me to code the design first and after that you'll assign ?

**Comment by AlfiyaSiddique** [comment]
@sushil-sagar05 that works as well. Assignment is not a problem I can assign you now only but just remember as it is a design change it will have a numerous back and fourth with feedback. So it will take time to merge.
Let me know what you say

**Comment by sushil-sagar05** [comment]
okay assign me i code that design and show you onto next 2-3 days. @AlfiyaSiddique

**Comment by sushil-sagar05** [comment]
Hey @AlfiyaSiddique Here i am attaching the new user Freindly Login Page of This Website .. 
previous
![TastyTrails-prevLoginPage](https://github.com/user-attachments/assets/9470c972-23c4-4e27-a116-bda921387a8f)
New
![TastyTrails-loginPage](https://github.com/user-attachments/assets/ba47dc17-ce65-4a6b-9748-4440d8e2fe16)
kindly Suggest if i make some changes in this

**Comment by AlfiyaSiddique** [comment]
@sushil-sagar05 looks great!
Just some Improvement:
1. Make word Review to Read
2. Make the buttons color as they were before
3. Use more like a real food image, the current one is animated.
4. Make sure it is responsive

Also please share the signup page design

**Comment by sushil-sagar05** [comment]
@AlfiyaSiddique Here is Updated ui of both and yes these both are responsive and better user friendly review it
Login
![Signin-TasyTrails](https://github.com/user-attachments/assets/d5740e53-7e53-4162-8f2c-93099a08d972)

Signin
![Register-TastyTrails](https://github.com/user-attachments/assets/d7f1b225-9a9d-4fae-b997-10f7811deba0)

**Comment by sushil-sagar05** [comment]
@AlfiyaSiddique it think  button color is better in prevous one i.e orange than the current one(red).. What you think?

**Comment by AlfiyaSiddique** [comment]
@sushil-sagar05 the signup form alignment is not good please fix that.
also, keep the card color white only with box-shadow you can try some borders as well.

I think the current button color looks good, orange seems completely different from the site theme.

And again the images do not look good, check the 404 image or the landing page pasta image you can also try some illustrations from the below sites:
https://undraw.co/
Freepik

Also you can raise PR I will give further feedback on PR
