### ISSUE TITLE
FEATURE: Welcome emails when signed up

### ISSUE THREAD

**Issue by sadath2001** [AlfiyaSiddique/TastyTrails#280]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

hi, i would like to implement the welcome email feature once new sign up is done.

### Component

/signup

### It should be implemented because

Would be good to have an onboarding email

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@sadath2001 is not an important feature right now.
Will let you know if needed or not, remind me in 2 days

**Comment by sadath2001** [comment]
hi @AlfiyaSiddique , can i work on this?

**Comment by AlfiyaSiddique** [comment]
Not decided yet, maybe not possible in this event

**Comment by sadath2001** [comment]
@AlfiyaSiddique , ok thanks, ill close this.

**Comment by AlfiyaSiddique** [comment]
@sadath2001 you can close the other otp email issue as well if you want, because the same above reply

**Comment by sadath2001** [comment]
Hi, sure. I'll close it out. Thanks
