### ISSUE TITLE
ENHANCEMENT: add hovering effects 

### ISSUE THREAD

**Issue by meghanakn473** [AlfiyaSiddique/TastyTrails#284]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

it highlights particular card which the user is looking into

### Component

recipes, main meal, small bit, healthy 

### It should be implemented because

.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@meghanaknthi473  this is a duplicate issue: #46
