### ISSUE TITLE
FEATURE: Add a testimonial page for increase trust !

### ISSUE THREAD

**Issue by Sawan-Kushwah** [AlfiyaSiddique/TastyTrails#285]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

By adding stronger testimonials, we can build user trust, improve credibility, and significantly enhance the overall experience on our platform

### Component

![Screenshot 2024-10-18 191732](https://github.com/user-attachments/assets/52a65bb1-cc7d-49ce-81b1-77586772c118)

### It should be implemented because

Something like this i can redesign it according to website theme and make it more beautiful
on clicking on the arrow cards slide with an animation with create great user impact 

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@Sawan-Kushwah as we do not have actual customers right now, this is not needed, Also it is a duplicate issue.
