### ISSUE TITLE
BUG: Near footer one semicolon visible 

### ISSUE THREAD

**Issue by Sivasaiklu** [AlfiyaSiddique/TastyTrails#287]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe your issue

> every page at the bottom it is showing semicolon (;) it has to be removed

### Steps to reproduce

Go to index page and see the error
where the semicolon present, remove that

### What was the expected result?

It was expected to not visible, but it is there

### Proposed solution

> a normal implementation 

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@Sivasaiklu duplicate issue #203 
Please feel free to comment on assigned issues if you are interested in solving them. It will get assigned if there are no updates from previous contributors.
Thanks for showing interest.
