### ISSUE TITLE
ENHANCEMENT: Improving the footer section.

### ISSUE THREAD

**Issue by userAdityaa** [AlfiyaSiddique/TastyTrails#289]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

The background should be added, for visible partition, font-style, icons for github and all should be comfortable enough to see. 

### Component
<img width="1440" alt="Screenshot 2024-10-20 at 7 31 46 PM" src="https://github.com/user-attachments/assets/651139c0-4e0c-4e43-a5a0-808c84bb9bab">

### It should be implemented becausee
The overall footer looks cluttered with not proper alignment, background and icons that are there. 

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by userAdityaa** [comment]
Hey @AlfiyaSiddique, Can I proceed with this issue ?

**Comment by AlfiyaSiddique** [comment]
@userAdityaa this is a duplicate issue: #15 
thanks for showing interest
