### ISSUE TITLE
code of conduct

### ISSUE THREAD

**Issue by Vyshnavi1322** [AlfiyaSiddique/TastyTrails#29]
No Code of  conduct assign me this i can do it

**Comment by AlfiyaSiddique** [comment]
Hello @Vyshnavi1322 
Welcome to TastyTrails. 🎉

Thanks for opening this issue.
Please go ahead!

**Comment by Vyshnavi1322** [comment]
please assign the label to it

**Comment by AnujSaha0111** [comment]
I want to work on the issue. Can you please assign it to me?
and please add gssoc-ext label

**Comment by AlfiyaSiddique** [comment]
Labels are assigned on PR and that is already done
