### ISSUE TITLE
ENHANCEMENT: Footer in mobile view is not responsive 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [AlfiyaSiddique/TastyTrails#290]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

![Screenshot_2024_1021_012654](https://github.com/user-attachments/assets/1541cc8a-cfa6-468a-95c9-f9720461f6a6)

### Component

Footer 

### It should be implemented because

For better user experience 

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@Sawan-Kushwah please go ahead and fix it as soon as possible.
there is an issue with navbar responsiveness as well. Can you fix that as well as part of this issue?

**Comment by Sawan-Kushwah** [comment]
@AlfiyaSiddique ofcourse I will do it!
