### ISSUE TITLE
Dedicated background color for the footer 

### ISSUE THREAD

**Issue by Sarthakkashyapp** [AlfiyaSiddique/TastyTrails#293]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

The footer needs a background colour it can be same as navbar or any other colour which matches the ui and theme of the website.

### Component

/footer

### It should be implemented because

Gives a more clean and professional look to the website also enhances footer apperance give a more clean look .

![Screenshot_2024-10-21-13-50-18-82_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/34f92feb-9c62-411b-a8b5-b2e995bf6968)

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@Sarthakkashyapp go ahead but please don't make it look odd
