### ISSUE TITLE
FEATURE: Implementation of Filter Session (Most Comments, Most Liked, Most Shared)

### ISSUE THREAD

**Issue by Anushka-Pote** [AlfiyaSiddique/TastyTrails#295]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Add a filter section to the recipes page that allows users to sort recipes based on the number of comments, likes, and shares.

### Component

Frontend:
Create a filter dropdown or buttons to choose the sorting criteria.
Fetch the sorted recipes from the API based on the selected filter.
Backend:
Create an API endpoint that accepts a query parameter for sorting.
Implement the logic to return recipes based on the selected sort order.
Database:
Ensure that the recipes have fields for comments, likes, and shares so that they can be sorted appropriately

### It should be implemented because

Why: Providing users with the ability to filter recipes based on engagement metrics helps them discover popular content easily.

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@Anushka-Pote this is a duplicate issue: #141
