### ISSUE TITLE
ENHANCEMENT: enhancement of Recipe boxes and navigation elements 

### ISSUE THREAD

**Issue by CM-Yuktha** [AlfiyaSiddique/TastyTrails#300]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

improving the UI of Recipe boxes and navigation element to make the page look more good by adding hovering effects

### Component

recipe boxes and nav elements

### It should be implemented because

improve user engagement 

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@CM-Yuktha Not required 
thanks for showing interest
