### ISSUE TITLE
ENHANCEMENT: Adding gssoc logo & updAted the readme

### ISSUE THREAD

**Issue by REHAN-18** [AlfiyaSiddique/TastyTrails#301]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

the readme is not updated & implementing the gssoc fest logo will enhance the readme ..

### Component

readme

### It should be implemented because

to stand out the readme will enhance thew repo

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by REHAN-18** [comment]
@AlfiyaSiddique yes but I will update the readme ass well as !!

**Comment by REHAN-18** [comment]
@AlfiyaSiddique add the step to how to contribute to this repo also!!

**Comment by REHAN-18** [comment]
@AlfiyaSiddique also update contributor on the readme

**Comment by AlfiyaSiddique** [comment]
@REHAN-18 These all are already in there.
thanks for showing interest!
Closing this issue
