### ISSUE TITLE
FEATURE: adding dark theme to the website

### ISSUE THREAD

**Issue by REHAN-18** [AlfiyaSiddique/TastyTrails#302]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

implementing the theme switcher button which user can change the theme as per her/his choice.

### Component

frontend 

### It should be implemented because

user can easily switched to dark mode ...which the user eye will not effect as much

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@REHAN-18 duplicate issue: #57
