### ISSUE TITLE
FEATURE: adding lazy loading and error boundary features 

### ISSUE THREAD

**Issue by vanshdhar999** [AlfiyaSiddique/TastyTrails#303]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Add lazy loading feature on the homepage to lazily load the components, to enhance the application loading time. Also add error handling features in case the pages or backend errors are recieved. the user should be greeted with a precise message to enhance web application functionality

### Component

/frontend folder

### It should be implemented because

It should be implemented because every good react project has a error handling feature and lazy loading for improving the functionality of the rendering of the webpage. These are essential features to be inside a web application.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [ ] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@vanshdhar999 lazy loading is already implemented
