### ISSUE TITLE
FEATURE: Navbar UI enhancement

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [AlfiyaSiddique/TastyTrails#305]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

In the navbar, I plan to implement a hover effect and animation on the logo, add an underline animation to the navigation items, enhance the style of the Login button, and apply styling to the arrow icon to give the overall navbar a more professional appearance.

### Component

I'm not sure I will be able to build these components.

### It should be implemented because

# Current Navbar 

![current-navbar](https://github.com/user-attachments/assets/86c79b31-abf3-49a1-acca-7ad19137d9b0)

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@biswajit-sarkar-007 no design change are needed
Thanks for showing interest
