### ISSUE TITLE
FEATURE: Features images added hover effect

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [AlfiyaSiddique/TastyTrails#306]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

In the Features section, I aim to implement modern hover effects on all images to make them look more professional and impressive, which will enhance the website.

# Screenshot

![feature-images-hover](https://github.com/user-attachments/assets/7eabf227-309d-4489-91e6-3c7aa16003b2)

### Component

i will build this.

### It should be implemented because

it neded to be

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@biswajit-sarkar-007 no hover effect is needed.
Thanks for showing interest
