### ISSUE TITLE
FEATURE: UI improvement of Footer

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [AlfiyaSiddique/TastyTrails#308]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

I want to redesign the footer from scratch, implement hover effects and animations for the logo, and ensure all navigation items are aligned with a justified position. Additionally, I will introduce captivating hover effects and animations for the social media icons.

# Screenshot

![redesigned-the-footer](https://github.com/user-attachments/assets/6ad23946-a976-4748-b16d-776c47efbdac)

### Component

i will built this.

### It should be implemented because

its make the whole website professional

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@biswajit-sarkar-007  development on footer is already going on #15
