### ISSUE TITLE
FEATURE: Contact Us Page

### ISSUE THREAD

**Issue by PriyanshuValiya** [AlfiyaSiddique/TastyTrails#312]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

From this feature user can mail you to ask any query..

### Component

/contactus

### It should be implemented because

It is a good sign to have interaction with our customers via mail.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@PriyanshuValiya the contact us page is not a requirement of the project, we already have the feedback form
thanks for showing interest
