### ISSUE TITLE
ENHANCEMENT: UI IMPROVEMENT OF "World's Best Dishes"

### ISSUE THREAD

**Issue by isimarjitsingh** [AlfiyaSiddique/TastyTrails#315]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

as i observed the designing of your "World's Best Dishes" is ordinary is well and good but i am able to add some more effects to provide smooth user experience.
AND  also i able to provide some more cards.

### Component

AS I AM BLE TO PROVIDE:-
- HOVER EFFECTS
- TRANSITION EFFECTS
- SOME CATCHY COLORE TO BORDER
- AS I ALSO ADD SOME MORE FEATURES SO THAT I ABLE TO PROVIDE CAROUSEL EFFECTS

### It should be implemented because

CURRENT DESIGNING:-
![Screenshot 2024-10-22 152715](https://github.com/user-attachments/assets/55d5fe06-fa04-46f7-8550-e5781970d654)

KINDLY ASSIGN ME THIS WORK UNDER GSSOC EXTD. SO THAT I WILL LOOK FORWARD TO CONTRIBUTE.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@isimarjitsingh no design changes are required also if you are interested you have to provide the figma design file of your proposed design first.
Thanks for showing interest
