### ISSUE TITLE
ENHANCEMENT:  UI IMPROVEMENT OF "SMALL BITES" PAGE

### ISSUE THREAD

**Issue by isimarjitsingh** [AlfiyaSiddique/TastyTrails#316]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

as i observed the designing of your "SMALL BITES" page is ordinary is well and good but i am able to add some more effects to provide smooth user experience.
and there is also a bug like some of the cards have same content and also don't have photos.

### Component

AS I AM BLE TO PROVIDE:-

- HOVER EFFECTS
- TRANSITION EFFECTS
- SOME CATCHY COLORE TO BORDER
- AS I ALSO ADD SOME MORE FEATURES SO THAT I ABLE TO PROVIDE CAROUSEL EFFECTS
- provide different photos and content

### It should be implemented because

CURRENT DESIGNING:-
![Screenshot 2024-10-22 153533](https://github.com/user-attachments/assets/1c09d59b-7361-4ef5-bf38-f21fef45ad98)

KINDLY ASSIGN ME THIS WORK UNDER GSSOC EXTD. SO THAT I WILL LOOK FORWARD TO CONTRIBUTE.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@isimarjitsingh no design changes are required also if you are interested you have to provide the figma design file of your proposed design first.
Thanks for showing interest
