### ISSUE TITLE
ENHANCEMENT:  Dynamic Search Feature

### ISSUE THREAD

**Issue by Gauravtb2253** [AlfiyaSiddique/TastyTrails#317]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

Searching the meals is not working 

### Component

searching the meals

### It should be implemented because

I would like to add dynamic search feature where in the search results will be filtered as soon as the user starts typing
It will increase the user experience

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@Gauravtb2253 This is already implemented and some filter implementation work is going on.
