### ISSUE TITLE
ENHANCEMENT: Redesigning of reciepe cards and adding hovering effects.

### ISSUE THREAD

**Issue by Son7c** [AlfiyaSiddique/TastyTrails#320]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

I can add hovering effect over reciepe cards, change the text alignments adding bold heading i.e reciepe name

### Component

/recipes

### It should be implemented because

The cards are very large and will look perfect if correctly designed.

![Screenshot 2024-10-23 002730](https://github.com/user-attachments/assets/a465c1bb-8ca5-4aac-9036-2d308b9cf61c)

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by Son7c** [comment]
@AlfiyaSiddique Please assign me this issue

**Comment by AlfiyaSiddique** [comment]
@Son7c you have to provide the design first
