### ISSUE TITLE
dark and light mode toggle 

### ISSUE THREAD

**Issue by sv410** [AlfiyaSiddique/TastyTrails#322]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

want to add dark and light mode toggle 

### Component

![WhatsApp Image 2024-10-15 at 12 05 39 PM (1)](https://github.com/user-attachments/assets/af1ed08c-4af3-4266-b15c-8d5272db9576)
![WhatsApp Image 2024-10-15 at 12 06 01 PM (1)](https://github.com/user-attachments/assets/c7f7de10-c8cb-40cb-9a6a-24445419ea5b)

### It should be implemented because

to get switch the web pages like to see in the dark and light mode 

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@sv410 this is an already opened issue #57
