### ISSUE TITLE
FEATURE: Dark and Light mode Toggle button

### ISSUE THREAD

**Issue by Sarthakkashyapp** [AlfiyaSiddique/TastyTrails#323]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Adding a Dark and Light mode Toggle button on the navbar enhances the user experience 

### Component

/Landing

### It should be implemented because

It is helpful for the ease in using website at night also add an extra functionality in the project.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@Sarthakkashyapp duplicate issue #57
