### ISSUE TITLE
ENHANCEMENT: enhancing the appearance of Footer

### ISSUE THREAD

**Issue by Sarthakkashyapp** [AlfiyaSiddique/TastyTrails#324]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

Improving the appearance of the footer rather than keeping everything in a single line footer it can be implemented like this : 

![Screenshot 2024-10-23 121508](https://github.com/user-attachments/assets/73a82e61-0248-4675-9ef4-37f8f94e9b13)

### Component

/footer

### It should be implemented because

It enhances the overall look of the footer as well as the website as the components of the footer get arranged properly and also looks professional enhances the overall appearance of the landing page. 

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@Sarthakkashyapp duplicate issue #15
