### ISSUE TITLE
FEATURE: In recipe cards  add toggle effect in like button while clicking on it with count of no of likes

### ISSUE THREAD

**Issue by Uvesh99** [AlfiyaSiddique/TastyTrails#325]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

In recipe cards like button toggle while clicking on it with count of no of  likes ,as you have already defined likes in recipe model, so we can do this .

### Component

Like Button in Recipe cards.

### It should be implemented because

A "like" button with a toggle and count feature enhances user engagement, provides valuable feedback, and adds a layer of interactivity to recipe cards or any other content-driven web applications. This simple feature, when implemented well, can make the app more engaging and user-friendly.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@Uvesh99 can you add some reference here

**Comment by Uvesh99** [comment]
# Issue: Like Button Functionality Not Working

# Description:
In the recipe cards component, the like button is not functioning as expected. Specifically, the following issues are observed:

Like count remains at 0: Clicking the like button does not update the like count displayed on the card.
Redirection Issue: Instead of toggling the like status, clicking the like button redirects the user directly to the recipe details page (/recipe/:recipeId).
Button does not toggle: The like button does not toggle or visually indicate when a user clicks on it, which creates a poor user experience.

# Steps to Reproduce:

Navigate to the page displaying the recipe cards.
Click on the like button below any recipe.
Observe that:
The like count does not increase.
The user is redirected to the recipe details page.
The like button does not visually change its state.

# Expected Behavior:

Clicking the like button should increase the like count.
The like button should toggle between liked and unliked states.
The user should not be redirected to another page upon clicking the like button.
# Screenshots:
![image](https://github.com/user-attachments/assets/f08c5d76-333e-4226-843a-e786baaea0b4)

This issue affects the user experience, as the functionality of the like button is essential for user engagement.

**Comment by AlfiyaSiddique** [comment]
@Uvesh99 It's not a bug but the feature is incomplete yet. This is an already open issue. Please check here #6
