### ISSUE TITLE
FEATURE: Feedback Implementation

### ISSUE THREAD

**Issue by haseebzaki-07** [AlfiyaSiddique/TastyTrails#331]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

users submitting the feedback should get stored in the database associated with them. Optional implementation if needed i.e. sending thank you emails to the users.

![Screenshot 2024-10-24 135807](https://github.com/user-attachments/assets/87e2d6ed-9e49-4df9-a7d1-5916fd014287)

### Component

backend/controllers/feedbackContoller

### It should be implemented because

Good feature fir a website like this and helps in testing the website for future upgrades and cutomizations

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
Okay, @haseebzaki-07 go ahead. Make sure to remove the email implementation and then add database implementation.

**Comment by haseebzaki-07** [comment]
sure @AlfiyaSiddique I will add the database implementation
