### ISSUE TITLE
BUG: Visitors should not be allowed to alter comments

### ISSUE THREAD

**Issue by haseebzaki-07** [AlfiyaSiddique/TastyTrails#332]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe your issue

Users visiting the website cannot delete other persons comments. A comment can only be deleted by the user that wrote it.
If the comments are hardcoded I would like to implement real backend for users to comment.

### Steps to reproduce

go to /recipe/:id
head to the comment section
click on the delele button 
The comment gets deleted.

### What was the expected result?

a user writing the comment should be allowed to delete.

### Proposed solution

I will create the necessary APIs for the purpose.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@haseebzaki-07 this is not hard coded, it is a backend bug.
Please fix it so that the delete button only appears if the comment is posted by a logged-in user

**Comment by haseebzaki-07** [comment]
sure @AlfiyaSiddique

**Comment by iitzIrFan** [comment]
@AlfiyaSiddique Shall I close this issue?

**Comment by haseebzaki-07** [comment]
@iitzIrFan It'll pe pushed soon don't close please

**Comment by iitzIrFan** [comment]
@haseebzaki-07 Ok
