### ISSUE TITLE
FEATURE: hover effect on social media icons

### ISSUE THREAD

**Issue by abhi200446** [AlfiyaSiddique/TastyTrails#333]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

i want to add hover at social media icons please assign @Alif

### Component

in the footer section in instagram ,linkedin etc

### It should be implemented because

for the better user experience 

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@abhi200446 not a requirement
