### ISSUE TITLE
FEATURE: Implement Carousel for User Testimonial for Tasty Trails as a Service

### ISSUE THREAD

**Issue by IkkiOcean** [AlfiyaSiddique/TastyTrails#334]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

We need to implement a carousel component to display user testimonials  on the homepage. This will enhance the user experience by allowing visitors to easily browse through reviews without overwhelming them with too much information at once.

### demo video:

https://github.com/user-attachments/assets/26637401-25c2-4f2a-a769-0b6e647c897d

### Component

/frontend/src/pages/landing.jsx

### It should be implemented because

- Enhanced User Experience
A carousel provides a visually appealing way to display reviews, making it easier for users to engage with feedback without feeling overwhelmed by information.

- Highlighting Positive Feedback
A carousel can be used strategically to showcase particularly glowing reviews, building trust and credibility for the brand or product.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@IkkiOcean  we do not have testimonials to show case

**Comment by IkkiOcean** [comment]
@AlfiyaSiddique we can implement the frontend for it and then backend for later development?

**Comment by AlfiyaSiddique** [comment]
Okay @IkkiOcean, go ahaed
