### ISSUE TITLE
ENHANCEMENT: Missing Eye Icon in Confirm Password Field for Password Visibility Toggle

### ISSUE THREAD

**Issue by Saurabhchaudhary9799** [AlfiyaSiddique/TastyTrails#335]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

Adding an eye icon to the "Confirm Password" field for toggling password visibility would ensure consistency across the form fields. This feature helps users ensure that they re-enter the correct password and reduces the chances of input errors during the account creation process.

### Component

/sign-up

### It should be implemented because

The "Confirm Password" field in the sign-up form does not have an eye icon that allows users to toggle password visibility. This inconsistency with the "Password" field, which includes an eye icon for toggling visibility, could confuse users and hinder the form-filling experience.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by Saurabhchaudhary9799** [comment]
hey @AlfiyaSiddique , could you please assign this to me ?

**Comment by AlfiyaSiddique** [comment]
@Saurabhchaudhary9799 not needed, there is already a show feature in the password field and if the password is mismatched it gives error so not needed
