### ISSUE TITLE
Improve the landing page to make it more appealing 

### ISSUE THREAD

**Issue by shubhagarwal1** [AlfiyaSiddique/TastyTrails#346]
<img width="333" alt="Screenshot 2024-10-25 at 4 44 07 AM" src="https://github.com/user-attachments/assets/07e259dc-4ab4-4ad9-90c3-843fb2297447">
ref: https://pinchofyum.com/

**Comment by akash205sharma** [comment]
Please Assign this task me, i want to contribute to this project

**Comment by AlfiyaSiddique** [comment]
@shubhagarwal1 please provide the design first

**Comment by AlfiyaSiddique** [comment]
closing this as some people already working on design
