### ISSUE TITLE
Revamp Your Website: Stylish Navbar Menu for Contributing to an Open-Source Project for a Sleek and Modern Design

### ISSUE THREAD

**Issue by khurshed07** [AlfiyaSiddique/TastyTrails#351]
## Effect :When We Hover on Navbar Menu Option we see the Effect
# Before Changes:
![Screenshot 2024-10-25 182710](https://github.com/user-attachments/assets/3e559f60-a416-4e1a-a283-fde1323d66e8)

# After Changes:
![Screenshot 2024-10-25 182418](https://github.com/user-attachments/assets/0c72e69d-773e-4b24-b234-c195403a8655)
![Screenshot 2024-10-25 182423](https://github.com/user-attachments/assets/dda25f25-fba1-4c3d-b755-adc49384b75d)
![Screenshot 2024-10-25 182428](https://github.com/user-attachments/assets/fd691e62-8a46-45e8-bfa0-c51c9a389819)
![Screenshot 2024-10-25 182434](https://github.com/user-attachments/assets/89e65ffc-32b3-4539-a489-5c558898218f)
![Screenshot 2024-10-25 182439](https://github.com/user-attachments/assets/75a36dd5-7ef2-4932-914c-2a8201ca1c3b)

Hi @AlfiyaSiddique 
I recently updated the navbar menu for your project to make it more attractive and user-friendly. Enhance readability, improve navigation, and give your site a visually appealing touch that stands out with these simple yet impactful design updates. I've attached screenshots of the changes, and I'd love to contribute to this enhancement to improve the overall design.

Please assign me to this task. It would be a great opportunity to contribute while enhancing my skills.
I'm looking forward to hearing back from you!
Best regards,
@khurshed07
https://github.com/khurshed07

**Comment by AlfiyaSiddique** [comment]
@khurshed07 not a requirement
