### ISSUE TITLE
➕Feature: Add a Scroll Progress Indicator Bar!

### ISSUE THREAD

**Issue by aslams2020** [AlfiyaSiddique/TastyTrails#356]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Hey @AlfiyaSiddique  
I want to add a **"Scroll Down Progress Bar"**

This feature adds a scroll down progress bar to the website, which visually indicates the user's progress as they scroll down the page. 
The progress bar enhances user experience by providing a clear visual cue of their location on the page and how much content remains to be viewed.

### ScreenShot 

Example Like this - 
As All the "component pages" are Large for scrolling, this Scroll Progress Bar Will Definitely Improve the user's scrolling experience and will also help to know their location on the page -

![image](https://github.com/XceeDesigns/Website/assets/131389695/0f92f30d-9dd7-464f-b1fb-6e854d1fe01c)

PLEASE ASSIGN THIS TO ME UNDER **Hactoberfest'24** 

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [] I'm a GSSOC'24 Ext contributor

**Comment by nataliakrein** [comment]
Could you please assign me this issue? Thanks

**Comment by AlfiyaSiddique** [comment]
@aslams2020 not a requirement

**Comment by AlfiyaSiddique** [comment]
@nataliakrein issues are assigned on first come basis. You can also open your own issues
