### ISSUE TITLE
FEATURE: No response while registering

### ISSUE THREAD

**Issue by raj-adi00** [AlfiyaSiddique/TastyTrails#357]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

When user try to register and while backen process there is no response. At that time signup button should show it is processing otherwise user will feel page is giving no response especially when there is slow internet.

### Component

I would disable signup button while backen process and show that it is loading. Same i will do with login button

### It should be implemented because

It makes website interactive

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by nataliakrein** [comment]
Could you please assign me this issue? Thanks

**Comment by AlfiyaSiddique** [comment]
@raj-adi00 instead of disabling the button can you make something like:
the screen fades with a loading animation when backend is processing?

**Comment by raj-adi00** [comment]
Okay I will do it. Please assign it to me
