### ISSUE TITLE
FEATURE: Verify email

### ISSUE THREAD

**Issue by raj-adi00** [AlfiyaSiddique/TastyTrails#358]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

If user enters email to register he can fill wrong email. So i will send email and save that code to mongoDB. IF that both code matches then only user can proceed to regsiter.

### Component

In signup page i will perform this process before user click signup option

### It should be implemented because

It prevents fraud account and using someone else email

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by rafiya2003** [comment]
Could you please assign me this issue? I would love to work on it and contribute to the project. Thanks

**Comment by AlfiyaSiddique** [comment]
@raj-adi00 not a decided feature for this event
