### ISSUE TITLE
FEATURE: Seed data

### ISSUE THREAD

**Issue by haseebzaki-07** [AlfiyaSiddique/TastyTrails#360]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Several pages of the website is empty in development because the local database is empty.
I want to seed some dummy data so that developers can have their time fixing the problems rather than seeing empty pages without data.
It will a command to run in the terminal and your local database will be up with all the datas that will be rendered on the site.

### Component

main meals, small bites and healthy pages.

![Screenshot 2024-10-26 115137](https://github.com/user-attachments/assets/6f42ffe2-9e50-46aa-a438-dee1a90e9153)

### It should be implemented because

it allows developers to improve these pages also which is not possible if they are empty. 

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@haseebzaki-07 are you talking about getting the deployed data to local through command?

**Comment by haseebzaki-07** [comment]
No they will be some dummy data hardcoded i the project. They will be seeded in the database with the command for development purpose

**Comment by AlfiyaSiddique** [comment]
Okay go ahead
