### ISSUE TITLE
ENHANCEMENT: Improve Image Upload Usability with Delete Option & Add Description Character Limit Counter

### ISSUE THREAD

**Issue by DubeyYash01** [AlfiyaSiddique/TastyTrails#363]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

Image Upload Controls: Add a "Delete" button next to the uploaded image preview, allowing users to easily remove or replace the image before submitting. This will improve the user experience by giving more control over image selection.

Character Counter for Description Field: Include a character counter below the description input field. This will help users stay within the maximum allowable character limit, enhancing clarity and ensuring that descriptions meet length requirements.

### Component

/add-recipe

### It should be implemented because

The proposed enhancements improve usability, streamline the submission process, and offer users clear feedback, which is essential for a positive experience. By implementing these features, the app will become more intuitive and accessible for users creating and submitting recipes.

Use Case:-
Image Upload Controls: When a user uploads an incorrect image or changes their mind, the lack of a "Delete" or "Remove" button forces them to navigate away and re-upload the recipe form from scratch. With a delete button, users can quickly correct image errors or make substitutions without losing their work.

Character Counter for Description Field: Users may unintentionally exceed the description character limit, leading to unexpected errors upon submission. The addition of a character counter will allow users to monitor and manage their input in real-time, preventing frustration and reducing form resubmission.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@DubeyYash01 no need for character limit and the image is required while submitting so need for delete option
