### ISSUE TITLE
ENHANCEMENT: Implement Helmet Middleware for Improved Security

### ISSUE THREAD

**Issue by samyak-aditya** [AlfiyaSiddique/TastyTrails#366]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

**Overview** : To improve the security of our Express application, we should implement the Helmet middleware. Helmet helps set various HTTP headers that protect against common vulnerabilities.

### Benefits:

- Adds security headers to HTTP responses, helping to mitigate risks such as:
- Cross-Site Scripting (XSS)
- Clickjacking
- Content-Type sniffing

Hey @AlfiyaSiddique Please Assign me this Task

### Component

- Cross-Site Scripting (XSS)
- Clickjacking
- Content-Type sniffing

### It should be implemented because

- Provides a foundational layer of security for our application.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by rafiya2003** [comment]
please assign me this issue

**Comment by AlfiyaSiddique** [comment]
@samyak-aditya go ahaed

**Comment by samyak-aditya** [comment]
Hey @AlfiyaSiddique I have raised the PR
