### ISSUE TITLE
Add table of contents section to the readme file 

### ISSUE THREAD

**Issue by T-Fathima** [AlfiyaSiddique/TastyTrails#368]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

I would like to add the table of section for better readability and easier navigation for the users.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

@AlfiyaSiddique I would like to work on it.
Please assign it to me under gssoc-ext and hacktoberfest.

**Comment by AlfiyaSiddique** [comment]
@T-Fathima not much content so not needed
