### ISSUE TITLE
ENHANCEMENT: Move profile page options to Navbar profile dropdown

### ISSUE THREAD

**Issue by mehul-m-prajapati** [AlfiyaSiddique/TastyTrails#376]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

Move profile page options to Navbar profile dropdown

### Component

Profile menu

### It should be implemented because

Better UI/UX

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

![p1](https://github.com/user-attachments/assets/a90df571-ac94-4081-b226-85a430b4249a)

**Comment by mehul-m-prajapati** [comment]
@AlfiyaSiddique: Please assign it to me

**Comment by AlfiyaSiddique** [comment]
@mehul-m-prajapati not required
