### ISSUE TITLE
ENHANCEMENT: Recipe Image delete and Re-Upload option

### ISSUE THREAD

**Issue by mehul-m-prajapati** [AlfiyaSiddique/TastyTrails#378]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

Recipe Image delete and Re-Upload option

### Component

Recipe Image 

### It should be implemented because

There is no option to change uploaded recipe image.
![p4](https://github.com/user-attachments/assets/af84b851-af13-4757-b224-79bc568c0044)

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by mehul-m-prajapati** [comment]
@AlfiyaSiddique: Please assign it to me

**Comment by AlfiyaSiddique** [comment]
@mehul-m-prajapati not required
