### ISSUE TITLE
FEATURE: Separate Page for Return policy

### ISSUE THREAD

**Issue by RachitSahu26** [AlfiyaSiddique/TastyTrails#384]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Is your feature request related to a problem? Please describe.
Currently, the website lacks a separate page dedicated to the return policy. Important details regarding returns, exchanges, and refunds may be hard to find or unclear if scattered across multiple sections. This can lead to confusion for users looking for guidance on how to return products or request refunds.

Describe the solution you'd like
I propose creating a dedicated Return Policy page accessible from the footer and relevant sections (e.g., checkout or order history). This page will contain:

Eligibility criteria for returns, exchanges, or refunds.
Instructions on how to initiate a return or exchange.
Timeframe for returns and refund processing.
Contact information for support in case of issues.
![Screenshot (418)](https://github.com/user-attachments/assets/bd65a62f-5809-423c-b358-a305f49a3ef7)

### Component

Create a New Route for the Return Policy Page
 Design the Return Policy Page Layout
Style the Page Using CSS
 Add a Link to the Footer

### It should be implemented because

fsdf

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@RachitSahu26 not needed
