### ISSUE TITLE
BUG: Fetching recipe comments fails in backend

### ISSUE THREAD

**Issue by mehul-m-prajapati** [AlfiyaSiddique/TastyTrails#389]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe your issue

Fetching recipe comments fails in backend

### Steps to reproduce

- Click on recipe card and see error in console.

### What was the expected result?

No error

### Proposed solution

Fix mongo query

![p1](https://github.com/user-attachments/assets/c1bca42f-a6c0-4962-b6b4-68ae5085ef1c)

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@mehul-m-prajapati go ahead

**Comment by AlfiyaSiddique** [comment]
@mehul-m-prajapati reopened this issue
