### ISSUE TITLE
FEATURE:  Add Contact Us Via E-Mail

### ISSUE THREAD

**Issue by PriyanshuValiya** [AlfiyaSiddique/TastyTrails#393]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

From this page, user can mail their issue, reviews, and queries directly from the website

**Previous Work**
![Screenshot 2024-10-25 125504](https://github.com/user-attachments/assets/42e6f423-dc15-4f55-8882-233c2efa2bfc)

### Component

/frontend/src/pages

### It should be implemented because

From this feature customer - the seller connection will enhance.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@PriyanshuValiya not needed
Thanks for showing interest
