### ISSUE TITLE
FEATURE: Subscribe to our newsletter

### ISSUE THREAD

**Issue by haseebzaki-07** [AlfiyaSiddique/TastyTrails#399]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Users entering their mail ids can subscribe to the platform and they get to receive mail of confirmation to their valid mail ids.

### Component

stay updated component at a suitable location on the page

### It should be implemented because

users are open to further updated of the platform if they are subscribed

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
Not a requiremnet
