### ISSUE TITLE
ENHANCEMENT: Footer Enhancement

### ISSUE THREAD

**Issue by amanver45** [AlfiyaSiddique/TastyTrails#401]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

The current footer design could be improved to enhance the overall user experience and align with modern design standards. Suggested improvements include refining the layout, updating colors, adding icons, and enhancing typography for better readability.

### Component

footer

### It should be implemented because

attractibe

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@amanver45 not needed
