### ISSUE TITLE
FEATURE: Like feature on the recipes

### ISSUE THREAD

**Issue by haseebzaki-07** [AlfiyaSiddique/TastyTrails#403]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

I want to add the like feature on the recipes so that users liking a recipe gets stored in the database also the users data gets that
liked recipe to show on the dashboard

### Component

/recipe/id page

### It should be implemented because

it is already present on the site I want to write its complete backend and frontend implementation

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
Already implemented

**Comment by haseebzaki-07** [comment]
@AlfiyaSiddique its not working tho

**Comment by AlfiyaSiddique** [comment]
what's not working explain in detail with a video

**Comment by haseebzaki-07** [comment]
https://github.com/user-attachments/assets/4050b77f-2df3-4df8-9b24-738007340c59

somethings wrong with the ID field of the recipes, I want to fix it

**Comment by AlfiyaSiddique** [comment]
@haseebzaki-07 working fine as shown below.  Seems like some data issue on your side, Create a new account and try again. No error was found in the console as well

https://github.com/user-attachments/assets/dd22e615-c058-4482-a532-dbc14321990a

**Comment by haseebzaki-07** [comment]
@AlfiyaSiddique Okay I will check
