### ISSUE TITLE
FEATURE: Add Filter Button to Recipes Page to Filter by Recipe Type (Main Meal, Small Bite, Healthy)

### ISSUE THREAD

**Issue by Uvesh99** [AlfiyaSiddique/TastyTrails#407]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

# Description 
The Recipes page currently supports searching recipes, but lacks a filter functionality to filter recipes by type. Adding a "Filter By" button would enhance user experience by allowing users to view recipes of a specific type, such as "Main Meal," "Small Bite," or "Healthy."

# Steps to Reproduce
- Go to the Recipes page.
- Notice that there's no option to filter recipes by type.

# Expected Behavior
- A "Filter By" button should be available, allowing users to filter recipes by type.
- Recipe types include:
    **Main Meal
    Small Bite
    Healthy**

- When a type is selected, only recipes of that type should be displayed.

### Component

Recipes Page: https://delightful-daifuku-a9f6ea.netlify.app/recipes

### It should be implemented because

Adding a "Filter By" button for recipe types (Main Meal, Small Bite, Healthy) is important because:

- Enhanced User Experience: Users can quickly locate the type of recipes they are interested in without needing to sift through all available recipes.
- Improved Efficiency: Filtering reduces the amount of information displayed, making the page more manageable and responsive to user needs.
- Alignment with User Intent: Users searching for specific types, such as "Healthy" recipes, can find relevant results faster, increasing satisfaction.
- Better Usability: This filter functionality aligns with modern web practices, making the page intuitive and user-friendly.

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@Uvesh99 there is a separate page for these filters so not needed
Thanks for showing interest
