### ISSUE TITLE
ENHANCEMENT: Make the contributor page user friendly or enhance the contributing page

### ISSUE THREAD

**Issue by souvikpramanikgit** [AlfiyaSiddique/TastyTrails#415]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

Make the contributor page user friendly or enhance the contributing page

### Component

contributor page

### It should be implemented because

As you can see the ui is not beautiful, so i want to add some style and some ui, and make like this

![image](https://github.com/user-attachments/assets/1305d845-04fd-4924-b21f-d6c82fbd9188)

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@souvikpramanikgit someone else already working on this
