### ISSUE TITLE
ENHANCEMENT: Add a loading screen when first open the page

### ISSUE THREAD

**Issue by souvikpramanikgit** [AlfiyaSiddique/TastyTrails#416]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

Add a loading screen when first open the page

### Component

i want to add a loading screen

### It should be implemented because

It enhance the ui of the website.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@souvikpramanikgit not a requirement
