### ISSUE TITLE
FEATURE: Testimonial Section Improvement✨

### ISSUE THREAD

**Issue by AnushkaChouhan25** [AlfiyaSiddique/TastyTrails#418]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Enhance the testimonial section by adding more profiles and implementing dynamic slide changes. Include a functional "Next" and "Previous" button for smooth navigation through testimonials.

### Component

![image](https://github.com/user-attachments/assets/aee6c0ca-9e70-4aab-9867-a024d4155e99)

### It should be implemented because

A visually appealing and interactive testimonial section that displays multiple profiles with smooth transitions, allowing users to navigate through testimonials easily.

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@AnushkaChouhan25 not a requirement.
Thanks for showing interest
