### ISSUE TITLE
FEATURE: Add Theme Toggle Button ✨

### ISSUE THREAD

**Issue by AnushkaChouhan25** [AlfiyaSiddique/TastyTrails#419]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Implement a theme toggle button on the website to allow users to switch between light and dark modes easily. Place the button in a prominent location, such as the top right corner, for easy access.

### Component

Theme toggle button 

### It should be implemented because

A functional and responsive theme toggle button that allows users to switch between light and dark modes, with consistent styling across all pages.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@AnushkaChouhan25 duplicate issue
