### ISSUE TITLE
FEATURE:  Create User Profile Page and Follow Feature

### ISSUE THREAD

**Issue by IkkiOcean** [AlfiyaSiddique/TastyTrails#424]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

#### Description
Implement a dedicated user profile page that displays information about individual users, including their bio, followed recipes, and feedback. Additionally, introduce a functionality that allows users to follow each other, enhancing community interaction and engagement on the platform.

#### Acceptance Criteria
1. **User Profile Page:**
   - Create a new route for user profiles, accessible via their username or user ID.
   - The profile page should display:
     - User's profile picture
     - Username
     - Bio
     - List of recipes created by the user
     - List of feedback given by the user
     - A "Follow" button if the current user is not already following them.

2. **Follow Feature:**
   - Implement functionality to follow/unfollow other users.
   - When the "Follow" button is clicked:
     - Update the backend to add the user to the follower list of the current user.
     - Change the button to "Unfollow" to indicate the current status.
   - Ensure that the list of followers and following is updated accordingly in the database.

### Component

it will be a new page. /UserPage.jsx since current component is configured for logged in user not others.

### It should be implemented because

1. **Enhanced User Engagement:**
   - Users can interact with each other by following profiles, leading to increased engagement on the platform. This creates a community feel and encourages users to explore content from others.

2. **Personalized Experience:**
   - By allowing users to follow others, they can curate their feed with recipes and feedback that interest them, providing a more tailored experience. This personalization can lead to higher user satisfaction and retention.

3. **Networking Opportunities:**
   - Users can connect with others who share similar interests in recipes and cooking, fostering networking opportunities. This can lead to collaborations, shared tips, and a supportive community.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by IkkiOcean** [comment]
right now there is no search feature, I will add the redirection from feedbacks present at homepage. is that fine?

**Comment by AlfiyaSiddique** [comment]
@IkkiOcean you can go ahead with this issue.

**Comment by AlfiyaSiddique** [comment]
>right now there is no search feature so I will add the redirection from feedbacks present at homepage. is that fine?

Not able to catch this can you describe more

**Comment by IkkiOcean** [comment]
@AlfiyaSiddique the profile page I suggested is profile page of other users , like you can view other members who are present on the site but we will need a feature to search them in future like you do on Instagram or LinkedIn. Since we dont have that feature right now. I am adding the route through the testimonial section (temporarily ) , as I plan to also make a search other users feature where you can search other users who also posts recipes.

**Comment by AlfiyaSiddique** [comment]
Okay great! understood
