### ISSUE TITLE
Creating terms of use page

### ISSUE THREAD

**Issue by Sawan-Kushwah** [AlfiyaSiddique/TastyTrails#427]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

We need to establish a "Terms of Use" page to define the legal framework governing the use of our website and services. This page will serve as a legal agreement between our company and users, outlining the terms under which our services are provided, user obligations, and limitations of liability.

### Component

i will add the link in footer

### It should be implemented because

This is a necessary page for legality ,

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by mehul-m-prajapati** [comment]
Seems to be a template copy paste everywhere https://github.com/Yashgabani845/hiring-portal/issues/312

**Comment by AlfiyaSiddique** [comment]
@Sawan-Kushwah there is already a policy page.
