### ISSUE TITLE
BUG: Page doesnt refresh automatically after deleting a recipie

### ISSUE THREAD

**Issue by sadath2001** [AlfiyaSiddique/TastyTrails#43]
Hello, I have found a bug.

**Problem:**

i observed that once a recipe has been deleted, it doesn't automatically go away from the view unless we refresh
Example:
I have deleted the recipe, but it doesnt go away
![image](https://github.com/user-attachments/assets/35f5647a-2552-40d7-a141-01bbaade6385)

Until i refresh this
![image](https://github.com/user-attachments/assets/259642b1-629c-4cf8-9894-44ea721f8001)

**Steps to recreate:**
- Create any recipie from the GUI
- Hit the delete recipie from your recipies
- Wait for some time, you wont see the recipie go away even after waiting
- Refresh the page and you'll find the recipie had gone

**Fix:**

Can be potentially fixed by calling the same page using navigator or calling the same page once the delete operation has been performed

Kindly assign this issue to me under GSSOC and hacktober fest.
Thank you

**Comment by AlfiyaSiddique** [comment]
Thanks for opening the issue @sadath2001 and the Pr as well.
Just one comment, Please wait until the issues is accepted and assigned to you and then raise PR.
I know it's obvious that this issue will be accepted but still please follow the process.
thanks Will review the PR soon

**Comment by sadath2001** [comment]
Hello @AlfiyaSiddique , thanks for the feedback. I will follow this henceforth.
