### ISSUE TITLE
FEATURE: Revamp Sign-Up Page with Verification Functionality

### ISSUE THREAD

**Issue by IkkiOcean** [AlfiyaSiddique/TastyTrails#430]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

**Objective:**  
Revise and improve the current sign-up page to add essential features for better user experience, account security, and database integrity.

### Scope of Changes

1. **Enforce Email Verification Requirement:**  
   - Introduce a mandatory email verification step before account creation. Users must click a verification link sent to their email address to complete the registration process.

2. **Username Availability Check:**  
   - Implement real-time validation to check if the chosen username is already taken. Users will be informed immediately when a username is unavailable.

3. **Email Availability Check:**  
   - Implement real-time validation to check if the entered email address is already associated with an existing account. Users will be notified immediately if the email is already registered in the database.

### Component

/signup page

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by IkkiOcean** [comment]
take it as demo:

https://github.com/user-attachments/assets/f79d0146-6971-4ecf-af27-65b47976bf07

**Comment by AlfiyaSiddique** [comment]
@IkkiOcean go ahead

**Comment by IkkiOcean** [comment]
@AlfiyaSiddique please merge these PR in the orders they are raised, cause 436 extends 435
