### ISSUE TITLE
FEATURE:  redesign the signing/signup pg

### ISSUE THREAD

**Issue by REHAN-18** [AlfiyaSiddique/TastyTrails#433]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

<img width="787" alt="Screenshot 2024-11-08 at 11 58 36 PM" src="https://github.com/user-attachments/assets/053de468-6c8c-4c9f-8d32-ba0b9f8204e8">
its looking old fashion I will redesign with modern aesthetic form !!

### Component

signup/signin

### It should be implemented because

it's looking dulll

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by REHAN-18** [comment]
@AlfiyaSiddique pls assign me !

**Comment by AlfiyaSiddique** [comment]
@REHAN-18  this is already done:
![image](https://github.com/user-attachments/assets/1c4d45d1-69cd-453c-8b17-c01923b0f3a9)
