### ISSUE TITLE
FEATURE: Implement User Search Page for Tasty Trails

### ISSUE THREAD

**Issue by IkkiOcean** [AlfiyaSiddique/TastyTrails#439]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

**Description:**
We need to create a user search page that allows users to search for other users on the Tasty Trails platform. This feature will enable users to find others based on their names.

**Requirements:**
1. **Search Input Field:**
   - A text input field for users to enter a search query (e.g., user name, etc.).
   - Include basic validation to ensure the input is not empty or malformed.

2. **Search Logic:**
   - The search should filter users based on the search query.
   - Search criteria may include user name, bio, cooking preferences, or any other profile details that are relevant.
   - Display an appropriate message if no matching users are found (e.g., "No users found").

3. **Search Results:**
   - Display a list of users that match the search query.
   - For each user, display basic profile information such as:
     - User name
     - Profile picture (optional)
     - Short bio or description (optional)
     - A link to the user's full profile page
   

### Component

/Search.jsx a new page

### It should be implemented because

Implementing a user search feature will allow Tasty Trails users to discover and connect with others who share similar interests in recipes, cooking styles, or dietary preferences. This functionality can increase community engagement, encourage social interaction, and improve the overall user experience on the platform.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@IkkiOcean go ahaed
