### ISSUE TITLE
BUG: Images dont clean up after the post/ recipie has been deleted

### ISSUE THREAD

**Issue by sadath2001** [AlfiyaSiddique/TastyTrails#44]
Hi I found a bug,

**Problem:**

Once we create a post, set the image, the image goes to our github repo as it has been configured.
But the problem comes when i delete the post, ideally it should also clean up the image in my repo

_example:_

![image](https://github.com/user-attachments/assets/17201eda-73d2-495b-a4cf-967abdbc4d65)
Once i deleted the above recipie, i expect it to delete the picture too from github

but it does not, see below
![image](https://github.com/user-attachments/assets/22985f81-1775-45f4-ba72-dc86b6abdcdf)

The images from deleted recipies too are present

**Steps to recreate:**

1. Create any recipie from the GUI
2. Hit the delete recipie from your recipies
3. Refresh the page and you'll find the recipie had gone
4. Go to your github repo, you'll see that image is still there

**Fix:**

Perhaps adding a delete command/ code would clear out the image being referred in the current post since we have sudo access in the github access token.

Kindly assign this to me under gssoc extended and hacktober fest

**Comment by AlfiyaSiddique** [comment]
Good Observation!
Please go ahead @sadath2001
