### ISSUE TITLE
BUG: Footer is sticky 

### ISSUE THREAD

**Issue by Hemraj-7** [AlfiyaSiddique/TastyTrails#440]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe your issue

Footer is sticky this is not looking good in the mobile version.
also footer is not responsive in the mobile phone.

![Screenshot 2024-11-09 193438](https://github.com/user-attachments/assets/1f84034c-c073-4269-a9a5-24112c2711ab)

Assign me this issue i want to work on this issue
thank you!

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@Hemraj-7 go ahead
