### ISSUE TITLE
FEATURE: Add Feature to View Following and Follower List

### ISSUE THREAD

**Issue by IkkiOcean** [AlfiyaSiddique/TastyTrails#441]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Here's an example of how you can write an issue for adding a feature to view the following and follower list:

---

### **Title:** Add Feature to View Following and Follower List

**Description:**  
We need to implement a feature that allows users to view their following and follower lists within the application. This feature should be accessible from the user profile and provide an easy-to-navigate interface to see who is following them and whom they are following.

**Acceptance Criteria:**

- **Following List:**  
  - The user can view a list of all the accounts they are following.
  - Each entry in the list should display the user's profile picture, username, and a link to their profile.
  
- **Follower List:**  
  - The user can view a list of all the accounts following them.
  - Each entry should also display the follower's profile picture, username, and a link to their profile.

### Component

new component , majority /Profile.jsx

### It should be implemented because

If there is already a "following" feature implemented, but there is no feature to view the **followers** or to easily see both lists together, here’s why it’s still beneficial to implement this feature:

### **Why this feature should be implemented:**

1. **Improved User Experience:**
   - **Visibility of Social Interactions:** Users expect to see both sides of their social connections—who they are following and who is following them. It creates a more complete and interactive profile experience.
   - **More Engaged Users:** Allowing users to see their followers can encourage them to engage more with people who are interested in their content or interactions. It also makes it easier for users to manage their social relationships within the app.

2. **Feature Completeness:**
   - **Consistency:** If the app already allows users to follow others, offering an option to view followers ensures consistency. It's common for most social platforms to show both following and follower lists for full transparency.
   - **Competitive Advantage:** Many social media and network applications provide this basic functionality as it is expected by users. Having this feature can make your app feel more polished and aligned with user expectations.

3. **User Engagement & Networking:**
   - **Better Interaction Opportunities:** Knowing who follows them allows users to engage with those people more effectively (e.g., replying to their followers' comments, messages, etc.). It also helps users to network more effectively within the platform.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@IkkiOcean go ahead
