### ISSUE TITLE
Github Workflow for issue template

### ISSUE THREAD

**Issue by sadath2001** [AlfiyaSiddique/TastyTrails#45]
Hi @AlfiyaSiddique , I would like to make a standard template for reporting issues / feature requests and add a section of it in the md file

**Question**: 

should i make it either under contributing md file or create a separate MD file ?

**Idea:**

The section can contain such as title, description, problem, idea/ solution to the problem, steps to recreate along with a few guuidelines/ required details in a standardized format. (ill try to make it as per industrial standard)

Kindly let me know your thoughts and assign this to me under GSSOC ext and Hacktoberfest.

**Comment by AlfiyaSiddique** [comment]
@sadath2001 we do not need a template for issues or feature in md file.
Adding a template for issues via github workflow will be better.
Let me know if you can do that

**Comment by sadath2001** [comment]
Hi @AlfiyaSiddique , sure I can do that via workflows.

**Comment by AlfiyaSiddique** [comment]
Great! Please Go ahead

**Comment by AlfiyaSiddique** [comment]
Please refer to StictHub for Issue Templates:
https://github.com/UBA-GCOEN/StichHub

**Comment by sadath2001** [comment]
![image](https://github.com/user-attachments/assets/82beb076-be37-43ad-b970-87ea9d504d53)
![image](https://github.com/user-attachments/assets/7dd7d40b-6cc4-4c4b-bde3-a3eca911032e)
![image](https://github.com/user-attachments/assets/cbf85974-b686-431c-866b-e2924453533f)
![image](https://github.com/user-attachments/assets/14caee18-78d9-4236-b992-1d0da2e3df4f)

Hi @AlfiyaSiddique ,
The above are the ones ive implemented, let me know if any modifications needed
