### ISSUE TITLE
Hovering on items

### ISSUE THREAD

**Issue by INam1995** [AlfiyaSiddique/TastyTrails#46]
![image](https://github.com/user-attachments/assets/dcfa02ac-f22b-4812-9054-eb3fc242cb49)
Hey @AlfiyaSiddique, the hover effect is currently missing on items, which affects the user experience. I can implement it to enhance the overall interactivity. Please assign this issue to me under the gssoc-ext label.

**Comment by AlfiyaSiddique** [comment]
Hello @INam1995 
Welcome to TatsyTrails.🎉
Thanks for opening this issue.

Where are you planning to add the hover effect in the recipes card or navbar items?

**Comment by INam1995** [comment]
I am planning to add the hover effect in the recipes card.

**Comment by AlfiyaSiddique** [comment]
Okay go ahead but do not add much transition just keep it simple.
Would be better if you could share some references before implementing.

**Comment by INam1995** [comment]
@AlfiyaSiddique please assign label with this issue

**Comment by AlfiyaSiddique** [comment]
Don't worry @INam1995 labels are assigned on PRs

**Comment by AlfiyaSiddique** [comment]
@INam1995 any updates?

**Comment by INam1995** [comment]
yes i am working upon it asap i will raise pr so please don't close issue

**Comment by INam1995** [comment]
@AlfiyaSiddique this project is not working on my localhost, i have tried too many times do you have any extra setup apart from common setup for mern project?

**Comment by INam1995** [comment]
@AlfiyaSiddique 
in this issue we have to show only three recipes or we can add more than three and then can add carousel sliding ?

**Comment by AlfiyaSiddique** [comment]
Caraousal feature is someone else implementing so you can add just hover

**Comment by INam1995** [comment]
okh done

**Comment by meghanakn473** [comment]
hi @AlfiyaSiddique  as @INam1995 as not responded from past 2 weeks, can u assign me the issue?

**Comment by INam1995** [comment]
@meghanakn473 I have completed i am going to raise a pr by tonight I have talked to @AlfiyaSiddique regarding issue also 
So don't consider it as I am not working

**Comment by INam1995** [comment]
@AlfiyaSiddique i have tried a lot but i am not getting recepies data have you did anything special 
even i have set all env variable which you have explained in .env.example file but still 
so please help me so that i can proceed asap i have reached out mentor of this project too but they have not responded till now so please help me

**Comment by AlfiyaSiddique** [comment]
@INam1995 have you set up your MongoDB cloud?
If yes then you have to add recipes by yourself first because your database do not have data it must not be showing up
