### ISSUE TITLE
Improve Login UI for Better Visual Appeal and User Experience

### ISSUE THREAD

**Issue by INam1995** [AlfiyaSiddique/TastyTrails#49]
![image](https://github.com/user-attachments/assets/fe03e097-d3e6-48f1-8f9f-9ad030a5b5b0)
Hey @AlfiyaSiddique, the login page UI could use some improvement. The large box in the background doesn't contribute positively to the design. I can enhance it to create a more appealing and user-friendly interface. Please assign this issue to me under gssoc-ext.

**Comment by AlfiyaSiddique** [comment]
@INam1995 Same reason as this:
https://github.com/AlfiyaSiddique/TastyTrails/issues/48#issuecomment-2392015991

**Comment by AlfiyaSiddique** [comment]
This issue is completed
