### ISSUE TITLE
Add pagination

### ISSUE THREAD

**Issue by ak3264114** [AlfiyaSiddique/TastyTrails#5]
Adding pagination to show recipes is an efficient way to handle large amounts of data in the future. Pagination reduces the number of records fetched and displayed at once, leading to faster loading times when we have a lot of data.

I would love to work on this issue. Please assign it to me.

Use gssoc 2024 ext label

**Comment by AlfiyaSiddique** [comment]
Hi @ak3264114 
Welcome to TastyTrails! 🎉

Go Ahead!
Make sure to test well!
