### ISSUE TITLE
Feature: Auto-Label Issues and Pull Requests on Creation

### ISSUE THREAD

**Issue by samyak-aditya** [AlfiyaSiddique/TastyTrails#50]
**Description:**
I propose to implements a new GitHub Actions workflow named "Greetings," which automatically greets users who open new issues or pull requests in this repository.

**Key Features:**
- **Automatic Greeting**: Users will receive an immediate acknowledgment when they create an issue or pull request. The messages are:
  - **For Issues**: "👋 Thank you for raising an issue! We appreciate your effort in helping us improve. Our team will review it shortly. Stay tuned!"
  - **For Pull Requests**: "🎉 Thank you for your contribution! Your pull request has been submitted successfully. A maintainer will review it as soon as possible. We appreciate your support in making this project better."

Hey @AlfiyaSiddique  please assign me this task with label "gssoc-ext", "Hacktoberfest-accepted" and "level1"

**Comment by AlfiyaSiddique** [comment]
@samyak-aditya 
This issue has already been implemented

**Comment by AlfiyaSiddique** [comment]
But I need one more feature in GitHub Workflow, described as follows.

Issues and PRs should get the labels `gssoc-ext` and `hacktoberfest-accepted` by the github-actions bot automatically after they are open .
@samyak-aditya  let me know if you can do this?

**Comment by samyak-aditya** [comment]
Hey @AlfiyaSiddique I would love to work on your described workflow
assign it to me with label "gssoc-ext", "Hacktoberfest-accepted" and "level2"

**Comment by AlfiyaSiddique** [comment]
Okay go ahead

**Comment by AlfiyaSiddique** [comment]
level Labels will be assigned on PR

**Comment by samyak-aditya** [comment]
Hey @AlfiyaSiddique I have raised the PR for this Task you asked for
Thanks
