### ISSUE TITLE
improve oneRecipe ui and add sort option 

### ISSUE THREAD

**Issue by harshit-G51102** [AlfiyaSiddique/TastyTrails#52]
Ui of single meal can be improved and sort by likes and shares button can be added near search box

**Comment by AlfiyaSiddique** [comment]
Hello @harshit-G51102 
Welcome to TastyTrails.🎉

Please provide the design first that you will implement for the one recipe UI.
And regarding the like and dislike feature, it is getting implemented in issue no. 6.
But yes you can work on the share feature but you have to implement it completely.
Let me know what you say.

**Comment by AlfiyaSiddique** [comment]
@harshit-G51102 please reply or this issue will be closed by tomorrow due to inactivity
