### ISSUE TITLE
Issue:Add the hover effect over the meal cards

### ISSUE THREAD

**Issue by Hh440** [AlfiyaSiddique/TastyTrails#53]
This effects will give them floating type view.

**Comment by Hh440** [comment]
https://github.com/user-attachments/assets/0fd20ef8-7843-42c7-9320-61321662ce9c

this is how the effect will look like and same effect can be applied for small card

**Comment by AlfiyaSiddique** [comment]
Duplicate of #46

**Comment by AlfiyaSiddique** [comment]
@Hh440 Please look for other issues, this is already taken
