### ISSUE TITLE
adding HOVER transition effect to every button of the page 

### ISSUE THREAD

**Issue by devxMani** [AlfiyaSiddique/TastyTrails#56]
Add GSOC EXT and Hacktoberfest Label to it

**Comment by AlfiyaSiddique** [comment]
There is already the color change effect on hover in all buttons.
Please describe first what kind of hover will you add @devxMani

**Comment by devxMani** [comment]
better animation effects to footer icons and buttons

**Comment by AlfiyaSiddique** [comment]
Please add some references @devxMani .

**Comment by devxMani** [comment]
https://github.com/user-attachments/assets/f09a2efd-1f4c-41ec-87b8-7444bd18f75b

like this in the footer and other button also

**Comment by AlfiyaSiddique** [comment]
@devxMani go ahead assigning to you

**Comment by devxMani** [comment]
@AlfiyaSiddique can you add level 2 to this

**Comment by AlfiyaSiddique** [comment]
@devxMani label level will be decide on your PR
