### ISSUE TITLE
{Open By Owner: Imp} Fix Cors policy Error for deploy preview.

### ISSUE THREAD

**Issue by AlfiyaSiddique** [AlfiyaSiddique/TastyTrails#58]
Currently, the backend is not working for deploy previews of Netlify because in Cors policy we only added the actual deployed URL.
Because of this, we are getting cors error on deploy previews and hence can't test with backend functionalities.

Opening this issue to be solved by you guys!
It is an easy one but as it is important, It carries a level 2 tag.
Will be assigned on a first come first serve basis.
The deadline is max 3 hours after you get assigned.
Thank you!

**Comment by smrutiranjanbhuyan** [comment]
Hi @AlfiyaSiddique 

I’d like to work on the CORS issue for the Netlify deploy previews. I’ll ensure it’s resolved within the deadline. Please assign it to me. Thank you!
