### ISSUE TITLE
Like Dislike feature

### ISSUE THREAD

**Issue by ak3264114** [AlfiyaSiddique/TastyTrails#6]
I would love to work on the like/dislike feature for the application.

The idea is to add a separate model for liked items, where the schema contains recipeId, userId, and a timeStamp. When the "Get Recipe" API is called, it will run a database query to return the like count. Additionally, under the user section, it will return the list of items liked by the user.

Please assign me this feature under GSSoC Extended.

**Comment by Shariar-Hasan** [comment]
If this issue still available, i would like to work on it

**Comment by AlfiyaSiddique** [comment]
@ak3264114 what's the update on this?

**Comment by AlfiyaSiddique** [comment]
@Shariar-Hasan assigning to you due to no updates from previous contributor

**Comment by AlfiyaSiddique** [comment]
@Shariar-Hasan please implement it soon

**Comment by Shariar-Hasan** [comment]
i might  not be able to do it now.
please assign anyone

**Comment by sadath2001** [comment]
Hey @AlfiyaSiddique , i can get this done in 2-3 days. if the time is okay, then you can assign this to me.

**Comment by sadath2001** [comment]
Hey @AlfiyaSiddique , kindly review.

https://drive.google.com/file/d/1iK9vctyd8k5Oq5A8tzGlNPWKRK2v_9nq/view?usp=sharing

**Comment by Saurabhchaudhary9799** [comment]
hey @AlfiyaSiddique , I want to work on this issue , could you please assign this to me ?

**Comment by AlfiyaSiddique** [comment]
@sadath2001 Looks great!
Some improvement!
No need to show the toast when liked or unlike the recipe, so remove that
You can raise PR will give further feedbacks on PR
