### ISSUE TITLE
Add the hover effect in footer and navbar

### ISSUE THREAD

**Issue by SaumyaSubham** [AlfiyaSiddique/TastyTrails#61]
Hii @AlfiyaSiddique 
I want to add the hover effect in the social media icons in the footer and the menu in the navbar so that the users can easily navigate it. And It also enhance the website into the next level.
Kindly assign me this

**Comment by AlfiyaSiddique** [comment]
@SaumyaSubham I think this issue will already be covered in one of the hover, navbar, or footer issues. If it will not then I will assign.

**Comment by AlfiyaSiddique** [comment]
This is a repeated issue, closing this off.
