### ISSUE TITLE
 Implement Like Feature for Recipes

### ISSUE THREAD

**Issue by smrutiranjanbhuyan** [AlfiyaSiddique/TastyTrails#69]
I want to implement a like feature for the recipe cards . This feature will allow users to like recipes, and the number of likes will be displayed on the recipe card.

**Comment by smrutiranjanbhuyan** [comment]
@AlfiyaSiddique   I would like to take on this issue to implement the like feature for the recipe cards.

**Comment by AlfiyaSiddique** [comment]
Duplicate of  #6
