### ISSUE TITLE
adding more healthy meals 

### ISSUE THREAD

**Issue by devxMani** [AlfiyaSiddique/TastyTrails#71]
![image](https://github.com/user-attachments/assets/ff2d4ee9-b8fb-494b-8f25-149c56795795)
add GSOC ext and hacktoberfest labels to it

**Comment by SaumyaSubham** [comment]
Hello @AlfiyaSiddique ,
I can add healthy meals like Dry Fruits or Oats etc. I'll try to add 4 to 5 meals. Can you assign me? under hacktoberfest and GSOC ext

**Comment by devxMani** [comment]
i can add 3-4 meals according to the page

**Comment by AlfiyaSiddique** [comment]
@devxMani can't assign this issue as it is not related to development and instead it is an usage of the web app.
