### ISSUE TITLE
fix the responsiveness of about the dish page

### ISSUE THREAD

**Issue by AyushSharma72** [AlfiyaSiddique/TastyTrails#72]
i want to fix the responsiveness of the about the dish page 

![image](https://github.com/user-attachments/assets/45273f62-fc42-4ad0-a7ea-40b35ac9357d)

for small screen devices
please assign this task to me @AlfiyaSiddique

**Comment by AlfiyaSiddique** [comment]
Hi @AyushSharma72 
Welcome to TastyTrails!🎉

Thanks for opening this issue.
Please Go ahead.

**Comment by AyushSharma72** [comment]
> Hi @AyushSharma72 Welcome to TastyTrails!🎉
> 
> Thanks for opening this issue. Please Go ahead.

Please add level

**Comment by AlfiyaSiddique** [comment]
levels will be added in PR
