### ISSUE TITLE
fix the responsiveness of the add recipe page

### ISSUE THREAD

**Issue by AyushSharma72** [AlfiyaSiddique/TastyTrails#73]
i want to fix the responsiveness if the add recipe page 

![image](https://github.com/user-attachments/assets/e22c36b0-c34f-451e-8b81-9cfdc8170520)
for small screen  devices

please assign this issue to me

**Comment by AlfiyaSiddique** [comment]
@AyushSharma72  Please Go Ahead!
Good issue to work on.

**Comment by AlfiyaSiddique** [comment]
@harshitkumargupta issues are assigned on a first come first serve basis.
I am sure you will find plenty of other issues to work on.  Thanks for showing interest!

**Comment by AyushSharma72** [comment]
> @AyushSharma72 Please Go Ahead! Good issue to work on.

Please add level
