### ISSUE TITLE
Testimonial section in website

### ISSUE THREAD

**Issue by bhatiatanish225** [AlfiyaSiddique/TastyTrails#75]
Hi @AlfiyaSiddique 
I will add a testimonial section in the website or our happy costumer section which will attract more users , so pls assign me this issue under hacktober fest.

**Comment by AlfiyaSiddique** [comment]
Hey @bhatiatanish225,
We do not need this section yet on our website as we do not have any real customer feedback as of now.
We are working on the feedback form, hopefully, once it is out we will get good number of customer feedback to display in a testimonial.
Till then I cannot assign this issue.
Thanks for showing your interest!

**Comment by sadath2001** [comment]
Hey @AlfiyaSiddique , since the feedback form is implemented now.can this be worked upon now?
I can do it if yes.

**Comment by AlfiyaSiddique** [comment]
Not needed yet @sadath2001
