### ISSUE TITLE
Implement rate limit on the backend api routes

### ISSUE THREAD

**Issue by Tholkappiar** [AlfiyaSiddique/TastyTrails#76]
**Suggested Improvements :** 

- Implementing rate limit on backend api routes to avoid dos attacks which will cause the backend to crash or causes unuseful computations 

**_**PS : Assign this issue to me under hacktoberfest 2024 , if you'r are comfortable with the above feature !**_**

**Comment by AlfiyaSiddique** [comment]
Hi @Tholkappiar 
Welcome to TastyTrails!🎉

Good Issue!
Please go ahead, also let me know how will you test this security feature?
