### ISSUE TITLE
Enhance Looks of Recipe added by user by making it like a card.

### ISSUE THREAD

**Issue by ZayedShahcode** [AlfiyaSiddique/TastyTrails#77]
So basically, i want to make the recipe's added by users to look like cards on user's profile page.
I also want to add a custom scroll bar also remove the scroll bar when not needed.
Improve UI and check responsiveness of overall page.
So @AlfiyaSiddique , assign me this issue under gssoc extd and hacktoberfest tags.

**Comment by ZayedShahcode** [comment]
I am speaking about this page
![image](https://github.com/user-attachments/assets/79742f8e-9c4f-44cc-9c61-ea547c2d7462)

**Comment by AlfiyaSiddique** [comment]
@ZayedShahcode 

I have some questions related to this issue:
Why do you think the card layout will look better than the current layout?
What is the problem with the current layout?

**Comment by ZayedShahcode** [comment]
There is no proper border for the recipe. The text is not prperly aligned. There is an unnecessary scroll bar. Update and Delete buttons can be made to look like proper buttons.

**Comment by AlfiyaSiddique** [comment]
@ZayedShahcode, any changes related to design either require a design demo or reference first, or you can directly start working on it. It will be improved based on our feedback. But don't expect it to merge soon because such changes take time to get accepted. Let me know what you say.

**Comment by AlfiyaSiddique** [comment]
@ZayedShahcode Please reply or this issue will be closed by tomorrow due to inactivity.
