### ISSUE TITLE
Enhancement: Improve footer and add a back to top button 

### ISSUE THREAD

**Issue by shubhagarwal1** [AlfiyaSiddique/TastyTrails#78]
**Enhancements Proposed**

- Enhance the website's footer for better usability and aesthetics by reorganizing content, improving responsiveness, and adding clear links to important sections like contact info, policies, and social media. 
- Include a "Back to Top" button to enhance navigation, allowing users to return quickly to the top of the page.

**Comment by AlfiyaSiddique** [comment]
@shubhagarwal1 
These issues are already in development.
Thanks for showing interset
