### ISSUE TITLE
Add OAuth - Google

### ISSUE THREAD

**Issue by sadath2001** [AlfiyaSiddique/TastyTrails#8]
Hi @AlfiyaSiddique 

I would like to add OAuth feature for this project.
Kindly add this under gssoc extended. and please assign me this issue

Thank you.

**Comment by AlfiyaSiddique** [comment]
Go ahead @sadath2001 
Assigning to you!

**Comment by Aditijainnn** [comment]
@AlfiyaSiddique please assign this to me

**Comment by sadath2001** [comment]
hi @AlfiyaSiddique , ill get this done by today EOD.

**Comment by sadath2001** [comment]
hi @AlfiyaSiddique , heres my progress. What changes do you suggest?

https://github.com/user-attachments/assets/aa55e735-4449-4ea6-a816-72fff9ed7c01

About the password, i was thinking, they can be redirected to change their password to a new password if they login via google.

**Comment by AlfiyaSiddique** [comment]
@sadath2001 the flow needs to be improved!
1. There should be a button on the signup page as well for signup with Google.
2. Those who had signed up with Google those users only can log in with Google.
3. If a user has not signed up with Google using an account and he/she tries to log in then the message -> you have not signed with Google using this account should appear.
4. When a user is signed up with Google he does not need to enter a password or username to log in.
5. Find a way how you will take the username of those users who will sign up with Google: One way is On the signup page when Sign up with Google is clicked just keep the username field and then the user clicks the signup with Google again after filing the username field and then take all the data and create an Account. Then from next time the user logs in he/she does not need a password to log in.
In your current flow, Even after logging in with Google, the user will need a username and password. If a user needs a password and username to log in then what's the use of OAuth login!
Let me know if you understood or not

**Comment by sadath2001** [comment]
Hi @AlfiyaSiddique , thank u for the feedback. , i understood.will take me some time to implement this, but yeah i will get it done,
