### ISSUE TITLE
in login adding option to signup with google

### ISSUE THREAD

**Issue by Aditijainnn** [AlfiyaSiddique/TastyTrails#84]
![image](https://github.com/user-attachments/assets/7b8758c0-bdb2-46ba-b68f-af86350a1810)
in this adding option to signup with google
please assign this to me under gssoc ext and hacktoberfest

**Comment by AlfiyaSiddique** [comment]
duplicate of #8 
@Aditijainnn  You can keep an eye on the #8 issue and comment that you are waiting to work on that issue. If I see no update of the assigned user we will assign the next user in the queue. 
Closing this issue
