### ISSUE TITLE
Add color to the nav bar and enhance the font to imporve the appearance of the website

### ISSUE THREAD

**Issue by riddhij0804** [AlfiyaSiddique/TastyTrails#86]
Adding a different color to the nav bar will make website visually appealing to the users.Additionally, making changes to the font will enhance the overall look of the website.
**This is a sample of how the website looks after changing the nav bar color.**
![nav bar color](https://github.com/user-attachments/assets/5544cb39-0566-4435-898e-d20f3a05942a)
**This is a sample of how the website looks after making changes to the font.**
![text](https://github.com/user-attachments/assets/07896f37-5167-491f-86c8-a65015346691)
**I would love to make these changes.**
**Could you please assign this issue to me.**

**Comment by AlfiyaSiddique** [comment]
@riddhij0804 Agree with the issue you opened.
But the proposed color does not look good as well.
Please share if you have any more color suggestions

**Comment by riddhij0804** [comment]
Thank you for the feedback! I understand that the proposed color might not fit the overall design. I’ve thought of an alternative approach:
1.We can use a lighter shade of the primary color #b91c1c and give it glass effect.
![navbar final](https://github.com/user-attachments/assets/3a13215f-947e-49ea-8829-37812b24527f)

2.We can use shades of grey and give it a glass effect.
![navbar final 2](https://github.com/user-attachments/assets/4bd6e0e4-4184-4a25-8944-bac2349ee966)

**3.We can use a gradient for the navbar from lighter to darker shade of #b91c1c (can try to give it a glass effect).**
I think this will look great.

**Also i would like to suggest that we can change the text alignment of the features and about us section to justify so that the content looks properly organized and sleek.**
Looking forward to working on this!

**Comment by riddhij0804** [comment]
@AlfiyaSiddique Could you assign me this issue?

**Comment by AlfiyaSiddique** [comment]
Okay  @riddhij0804 go ahaed

**Comment by riddhij0804** [comment]
Hello mam .Thank you for assigning. I am new to opensource. I did try npm i install and npm start but its not working. Could you kindly guide me regarding how can I run the project on my device.

**Comment by MohammedMusharraf11** [comment]
you can navigate to frontend dir and then 
`npm i` followed by `npm run dev`

**Comment by AlfiyaSiddique** [comment]
@riddhij0804 does your issue get resolved? Are you unblocked?

**Comment by riddhij0804** [comment]
Yes mam. Thank you for helping.I will try to do this till saturday.

**Comment by AlfiyaSiddique** [comment]
Sure, take your time @riddhij0804 .
Thanks, @MohammedMusharraf11 for the assistance.

**Comment by riddhij0804** [comment]
@AlfiyaSiddique 
**Mam, this is how the navbar is looking.**
Upon hovering over recipes, main meals, small bites, healthy the color changes to white.
![tasty](https://github.com/user-attachments/assets/034e2fe4-db5d-4294-b323-b6f4c27362b0)
I have also changed the font family of "Where Flavour meets Perfection"
**Justified these texts :**
![justify 1](https://github.com/user-attachments/assets/d5aa91f5-c621-4451-a7d6-a1f3d01415f2)
![justify 2](https://github.com/user-attachments/assets/e3f3b35a-0f9b-4579-8a44-f53bd88ebfd8)
**Could you assign me a level?
Can I send a PR?**

**Comment by AlfiyaSiddique** [comment]
@riddhij0804 The background of the navbar is not looking good, do not add a gradient background to it keep it consistent.
After this change you can open PR, Label will be assigned to PR.

**Comment by riddhij0804** [comment]
Ok mam. I will try to send it tomorrow.
