### ISSUE TITLE
Cors Error (Important & Urgent to fix)

### ISSUE THREAD

**Issue by AlfiyaSiddique** [AlfiyaSiddique/TastyTrails#88]
We are again getting a Cors error on the deployed URL as well as the deploy preview.
Please fix this issue as urgent as possible.

**Comment by yours7himanshu** [comment]
Please assign this issue to me I will fix it asap

**Comment by AlfiyaSiddique** [comment]
@yours7himanshu 
Please Go ahead and fix this on priority!

**Comment by yours7himanshu** [comment]
> @yours7himanshu Please Go ahead and fix this on priority!

Yaa don't worry I will fix it asap!!

**Comment by yours7himanshu** [comment]
@AlfiyaSiddique when i am hitting the deployed backend Url with the api route like - https://tastytrails.onrender.com/api/recipes
So I thinnk that might is causing the problem...check the image i sent -
![Screenshot from 2024-10-05 18-04-17](https://github.com/user-attachments/assets/08c03dea-7237-41c3-b609-10074abf2689)

**Comment by AlfiyaSiddique** [comment]
Okay, understand this is a deployment issue, not cors! Hence not a code issue. I will fix it.
Thanks for drawing my attention to this
And I apologize as no points can be given on this!

**Comment by AlfiyaSiddique** [comment]
@yours7himanshu can you quickly remove the backend URL file in common folder and use env to populate the backend you are
Can you do this asap?

**Comment by AlfiyaSiddique** [comment]
@yours7himanshu Sure please go ahead and create a PR for this asap. Assigning to you again!

**Comment by yours7himanshu** [comment]
> @yours7himanshu can you quickly remove the backend URL file in common folder and use env to populate the backend URL and fix the frontend code to retrieve backend url Can you do this asap?

Ya I had even done that when I was solving cors problem😄.So should I raise PR for that?

**Comment by AlfiyaSiddique** [comment]
Yes please go ahead

**Comment by yours7himanshu** [comment]
> Yes please go ahead

@AlfiyaSiddique I had created a PR and included the .env file for backendUrl just this ones so that u got the idea.. please make sure that the next time u commit changes please hide my .env file that I had included.. because env file mai sensitive data hota h aur hm nii chahte ho koi GitHub ke through access krpaye Maine abhi bs apko show krne ke liye kiya h jisse aap samjh jaaye kaise hua h
