### ISSUE TITLE
Missing navigation to Home Page 

### ISSUE THREAD

**Issue by ananyag309** [AlfiyaSiddique/TastyTrails#89]
There is currently no direct navigation link to the Home Page from Recipies, small bites etc this absence can create a less intuitive user experience, making it difficult for users to return to the main page.

![back home](https://github.com/user-attachments/assets/bf61321d-f629-47e7-aec3-0d1eb2202fc9)

**Comment by AlfiyaSiddique** [comment]
@ananyag309  On clicking on the TastyTrails text of Navbar it navigates back to the homepage.
So not a valid issue.
Closing this issue.
