### ISSUE TITLE
Website Opening Page - Intro

### ISSUE THREAD

**Issue by neeru24** [AlfiyaSiddique/TastyTrails#94]
Hi, 
I think the spelling is wrong there.. it's FLAVOUR not FLOVOUR..
Then it's just static... I want to add animation and hover glow up type effect to this part... if possible typing svg. 

![image](https://github.com/user-attachments/assets/73bbda95-8c38-4c05-9c00-149ab74836be)

Kindly assign me this issue.

**Comment by AlfiyaSiddique** [comment]
@neeru24 any change to design first require the design demo or reference so please provide that and the typo is too small an issue to be assigned

**Comment by AlfiyaSiddique** [comment]
@neeru24 any updates? If not can we close the issue

**Comment by neeru24** [comment]
> @neeru24 any updates? If not can we close the issue

I was busy with exams. I'm working on it
I'll submit a PR  by tonight
