### ISSUE TITLE
Social media icon - Footer

### ISSUE THREAD

**Issue by neeru24** [AlfiyaSiddique/TastyTrails#95]
The second issue, I came across is that the size of these social media handles is way small and not recognisable..... I can make change these and make them look more good, adding some hover effect or actual logo type.

![image](https://github.com/user-attachments/assets/51064d8b-4573-4af0-85f1-1b4fbf1a3a36)

**Comment by AlfiyaSiddique** [comment]
Changes in footer is under development so not needed
