### ISSUE TITLE
Add Responsive Navbar with Menubar

### ISSUE THREAD

**Issue by Atharv-110** [AlfiyaSiddique/TastyTrails#96]
![image](https://github.com/user-attachments/assets/cf9669f4-e8d2-45cf-b129-93dbb13b3cbc)

Resolution for this:
I will add few tailwind styles and make it more interactive like open and close of menu bar

@AlfiyaSiddique Please assign this issue to me and add Hacktoberfest label.

Thanks.

**Comment by AlfiyaSiddique** [comment]
@Atharv-110 Go Ahead!
Assigning to you.
