### ISSUE TITLE
Make changes in login form

### ISSUE THREAD

**Issue by Aditijainnn** [AlfiyaSiddique/TastyTrails#99]
![image](https://github.com/user-attachments/assets/542069a8-4dce-4f4c-891c-7da0204da3ab)
in this there is no option of going back to home so adding that
assign this to me under gssoc ext and hacktoberfest

**Comment by harshitkumargupta** [comment]
HI @Aditijainnn ,
Please assign me this issue under Hacktoberfest Tag.

**Comment by AlfiyaSiddique** [comment]
@Aditijainnn  On clicking on the TastyTrails text of Navbar it navigates back to the homepage.
So not a valid issue.
Closing this issue.
